import React from 'react';
import { Page, Text, View, Document, StyleSheet, Image } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: {
    padding: 40,
    paddingBottom: 60, // Space for footer
    fontFamily: 'Helvetica',
    fontSize: 10,
    color: '#333',
  },
  header: {
    marginBottom: 30,
    borderBottomWidth: 2,
    borderBottomColor: '#2563eb',
    paddingBottom: 10,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#1e3a8a', // blue-900
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 12,
    color: '#64748b', // slate-500
  },
  section: {
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    backgroundColor: '#f1f5f9',
    padding: 8,
    marginBottom: 10,
    color: '#0f172a',
  },
  itemRow: {
    flexDirection: 'row',
    marginBottom: 8,
    alignItems: 'center',
  },
  checkbox: {
    width: 12,
    height: 12,
    borderWidth: 1,
    borderColor: '#94a3b8',
    marginRight: 10,
  },
  itemText: {
    fontSize: 10,
    flex: 1,
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: 'center',
    fontSize: 8,
    color: '#9ca3af',
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
    paddingTop: 10,
  },
});

const CHECKLIST_ITEMS = {
  "Personal Hygiene & Staff": [
    "Staff are wearing clean, suitable protective clothing (aprons, hairnets).",
    "No jewelry or watches worn by food handlers (plain wedding bands exempt).",
    "Handwashing sinks are accessible, stocked with soap, hot water, and paper towels.",
    "Staff wash hands after touching raw food, waste, or phones.",
    "Illness reporting policy is signed and understood by all staff.",
    "Cuts/sores covered with blue water-proof detectable plasters."
  ],
  "Food Storage & Temperature": [
    "Fridges verified at ≤ 4°C and freezers at ≤ -18°C.",
    "Raw meat/fish stored BELOW ready-to-eat foods to prevent drip contamination.",
    "All prepared foods are labeled with a 'Use By' or 'Production' date.",
    "Dry storage is off the floor, pest-proof, and cool.",
    "FIFO (First-In, First-Out) system is actively used.",
    "Deliveries checked for temperature and package integrity upon arrival."
  ],
  "Food Preparation & Cooking": [
    "Separate cutting boards used for raw meat (red) and vegetables (green/brown).",
    "Core cooking temperatures are checked with a calibrated probe thermometer.",
    "Hot holding verified at ≥ 63°C.",
    "Rapid cooling methods (blast chiller/ice bath) used for cooked foods.",
    "Frozen food is thawed in the fridge, not at room temperature."
  ],
  "Cleaning & Sanitation": [
    "Cleaning schedule is up-to-date and signed off by management.",
    "Sanitizer contact time (e.g., 30s) is known and respected.",
    "Dishwasher is clean, and rinse temperature reaches ≥ 82°C.",
    "Waste bins are not overflowing and have lids.",
    "Pest control checks are current; no signs of infestation."
  ],
  "Allergen Management (2026 Focus)": [
    "Allergen matrix is accurate and available for all menu items.",
    "Staff can confidently explain cross-contamination risks to customers.",
    "Separate utensils/area designated for allergen-free prep.",
    "Packaged foods for delivery have full ingredient labeling.",
    "Allergen spillages cleaned immediately with dedicated kit."
  ],
  "Traceability & Digital Records (NEW)": [
    "Digital monitoring logs (temp/cleaning) are up-to-date and backed up.",
    "Supplier invoices/delivery notes retained for 12 months.",
    "Batch codes recorded for high-risk items (meat/shellfish/eggs).",
    "Mock recall procedure documented and tested annually."
  ],
  "Maintenance & Infrastructure (NEW)": [
    "Thermometers calibrated monthly (ice point method) and logged.",
    "No flaking paint, cracked tiles, or rust in food preparation areas.",
    "Ventilation/Extraction hoods are clean and grease-free.",
    "Lighting is adequate and shatter-proof in all food handling areas."
  ]
};

const ChecklistDocument = () => (
  <Document>
    <Page size="A4" style={styles.page} wrap>
      <View style={styles.header} fixed>
        <Text style={styles.title}>2026 Food Safety Inspection Checklist</Text>
        <Text style={styles.subtitle}>Audit-Ready Self-Assessment Tool | ilovehaccp.com</Text>
      </View>

      {Object.entries(CHECKLIST_ITEMS).map(([category, items], i) => (
        <View key={i} style={styles.section} wrap={false}>
          <Text style={styles.sectionTitle}>{category}</Text>
          {items.map((item, j) => (
            <View key={j} style={styles.itemRow}>
              <View style={styles.checkbox} />
              <Text style={styles.itemText}>{item}</Text>
            </View>
          ))}
        </View>
      ))}

      <View style={styles.footer} fixed>
        <Text>Generated by iLoveHACCP - The easiest way to build your full HACCP plan.</Text>
        <Text>Visit www.ilovehaccp.com to create your complete customized documentation.</Text>
      </View>
    </Page>
  </Document>
);

export default ChecklistDocument;
