import React from 'react';
import { Page, Text, View, Document, StyleSheet, Image, Font } from '@react-pdf/renderer';

// Create styles
const styles = StyleSheet.create({
  page: {
    flexDirection: 'column',
    backgroundColor: '#FFFFFF',
    padding: 40,
    fontFamily: 'Helvetica',
    fontSize: 10,
    lineHeight: 1.4,
  },
  coverPage: {
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    height: '100%',
    padding: 40,
    backgroundColor: '#FFFFFF',
  },
  coverTitle: {
    fontSize: 32,
    fontWeight: 'bold',
    marginBottom: 20,
    color: '#1E3A8A', // Blue-900
    textAlign: 'center',
  },
  coverSubtitle: {
    fontSize: 18,
    color: '#6B7280',
    marginBottom: 40,
    textAlign: 'center',
  },
  coverMeta: {
    fontSize: 12,
    color: '#374151',
    marginBottom: 10,
    textAlign: 'center',
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 15,
    marginTop: 20,
    color: '#1E3A8A',
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
    paddingBottom: 5,
  },
  subHeader: {
    fontSize: 12,
    fontWeight: 'bold',
    marginBottom: 8,
    marginTop: 10,
    color: '#374151',
  },
  text: {
    marginBottom: 8,
    color: '#374151',
    textAlign: 'justify',
  },
  table: {
    display: 'flex',
    width: 'auto',
    borderStyle: 'solid',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    marginTop: 10,
    marginBottom: 10,
  },
  tableRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
    minHeight: 25,
    alignItems: 'center',
  },
  tableHeaderRow: {
    flexDirection: 'row',
    backgroundColor: '#F3F4F6',
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
    minHeight: 30,
    alignItems: 'center',
  },
  tableColHeader: {
    padding: 5,
    fontSize: 8,
    fontWeight: 'bold',
    color: '#111827',
  },
  tableCol: {
    padding: 5,
    fontSize: 8,
    color: '#374151',
  },
  ccpBadge: {
    backgroundColor: '#FEE2E2',
    color: '#B91C1C',
    paddingHorizontal: 4,
    paddingVertical: 1,
    borderRadius: 2,
    fontWeight: 'bold',
    fontSize: 8,
    textAlign: 'center',
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: 'center',
    color: '#9CA3AF',
    fontSize: 8,
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
    paddingTop: 10,
  },
  pageNumber: {
    position: 'absolute',
    bottom: 30,
    right: 40,
    fontSize: 8,
    color: '#9CA3AF',
  }
});

interface Props {
  data: {
    businessName: string;
    productName: string;
    productDescription: string;
    intendedUse: string;
    storageType: string;
    analysis: any[];
    fullPlan?: {
      executive_summary: string;
      prerequisite_programs: { program: string; details: string }[];
      process_flow_narrative: string;
      hazard_analysis: any[];
      ccp_summary: {
        ccp_step: string;
        hazard: string;
        critical_limit: string;
        monitoring: string;
        corrective_action: string;
      }[];
    } | null;
  };
}

const HACCPDocument = ({ data }: Props) => {
  const { fullPlan } = data;

  return (
    <Document>
      {/* PAGE 1: COVER PAGE */}
      <Page size="A4" style={styles.coverPage}>
        <View style={{ marginBottom: 20 }}>
          <Text style={styles.coverTitle}>HACCP Plan</Text>
          <Text style={styles.coverSubtitle}>Food Safety Management System</Text>
        </View>

        <View style={{ padding: 20, width: '100%', alignItems: 'center' }}>
          <Text style={styles.coverMeta}>Prepared for:</Text>
          <Text style={{ ...styles.coverTitle, fontSize: 24, marginBottom: 40 }}>{data.businessName}</Text>
          
          <Text style={styles.coverMeta}>Date Generated: {new Date().toLocaleDateString()}</Text>
          <Text style={styles.coverMeta}>Reference Standard: Codex Alimentarius</Text>
        </View>

        <Text style={styles.footer}>
          Generated by ilovehaccp.com - Professional AI-Powered Food Safety
        </Text>
      </Page>

      {/* PAGE 2: EXECUTIVE SUMMARY & PRODUCT DESCRIPTION */}
      <Page size="A4" style={styles.page}>
        <Text style={styles.sectionTitle}>1. Executive Summary</Text>
        <Text style={styles.text}>
          {fullPlan?.executive_summary || "This HACCP plan has been designed to control food safety hazards."}
        </Text>

        <Text style={styles.sectionTitle}>2. Product Description</Text>
        <View style={{ marginBottom: 10 }}>
          <Text style={styles.subHeader}>Product Name</Text>
          <Text style={styles.text}>{data.productName}</Text>

          <Text style={styles.subHeader}>Description</Text>
          <Text style={styles.text}>{data.productDescription}</Text>

          <Text style={styles.subHeader}>Intended Use</Text>
          <Text style={styles.text}>{data.intendedUse}</Text>

          <Text style={styles.subHeader}>Storage Conditions</Text>
          <Text style={styles.text}>{data.storageType}</Text>
        </View>

        <Text style={styles.sectionTitle}>3. Process Flow Narrative</Text>
        <Text style={styles.text}>
          {fullPlan?.process_flow_narrative || "The process flow involves receiving, storage, preparation, cooking, and service."}
        </Text>

        <Text style={styles.pageNumber} render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`} fixed />
        <Text style={styles.footer} fixed>Generated by ilovehaccp.com</Text>
      </Page>

      {/* PAGE 3: PREREQUISITE PROGRAMS */}
      <Page size="A4" style={styles.page}>
        <Text style={styles.sectionTitle}>4. Prerequisite Programs (PRPs)</Text>
        <Text style={{ ...styles.text, marginBottom: 15 }}>
          The following prerequisite programs are established to ensure a hygienic environment for food production:
        </Text>

        {fullPlan?.prerequisite_programs?.map((prp, index) => (
          <View key={index} style={{ marginBottom: 10 }}>
            <Text style={styles.subHeader}>{prp.program}</Text>
            <Text style={styles.text}>{prp.details}</Text>
          </View>
        ))}

        <Text style={styles.pageNumber} render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`} fixed />
        <Text style={styles.footer} fixed>Generated by ilovehaccp.com</Text>
      </Page>

      {/* PAGE 4: HAZARD ANALYSIS TABLE (Landscape usually better, but sticking to A4 Portrait for consistency if not too wide) */}
      <Page size="A4" style={styles.page}>
        <Text style={styles.sectionTitle}>5. Hazard Analysis</Text>

        <View style={styles.table}>
          <View style={styles.tableHeaderRow}>
            <View style={{ ...styles.tableColHeader, width: '20%' }}><Text>Process Step</Text></View>
            <View style={{ ...styles.tableColHeader, width: '30%' }}><Text>Hazards</Text></View>
            <View style={{ ...styles.tableColHeader, width: '30%' }}><Text>Control Measures</Text></View>
            <View style={{ ...styles.tableColHeader, width: '10%' }}><Text>CCP?</Text></View>
            <View style={{ ...styles.tableColHeader, width: '10%' }}><Text>Limit</Text></View>
          </View>

          {data.analysis.map((item, index) => (
            <View key={index} style={styles.tableRow}>
              <View style={{ ...styles.tableCol, width: '20%' }}><Text>{item.step_name}</Text></View>
              <View style={{ ...styles.tableCol, width: '30%' }}><Text>{item.hazards}</Text></View>
              <View style={{ ...styles.tableCol, width: '30%' }}><Text>{item.control_measure}</Text></View>
              <View style={{ ...styles.tableCol, width: '10%' }}>
                {item.is_ccp ? (
                  <Text style={styles.ccpBadge}>YES</Text>
                ) : (
                  <Text>No</Text>
                )}
              </View>
              <View style={{ ...styles.tableCol, width: '10%' }}><Text>{item.critical_limit || 'N/A'}</Text></View>
            </View>
          ))}
        </View>

        <Text style={styles.pageNumber} render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`} fixed />
        <Text style={styles.footer} fixed>Generated by ilovehaccp.com</Text>
      </Page>

      {/* PAGE 5: HACCP PLAN (CCP SUMMARY) */}
      <Page size="A4" style={styles.page}>
        <Text style={styles.sectionTitle}>6. HACCP Plan (CCP Summary)</Text>
        <Text style={{ ...styles.text, marginBottom: 15 }}>
          Critical Control Points (CCPs) identified in the hazard analysis are controlled as follows:
        </Text>

        {fullPlan?.ccp_summary && fullPlan.ccp_summary.length > 0 ? (
          fullPlan.ccp_summary.map((ccp, index) => (
            <View key={index} style={{ marginBottom: 20, border: '1px solid #E5E7EB', borderRadius: 4, padding: 10 }}>
              <View style={{ flexDirection: 'row', justifyContent: 'space-between', marginBottom: 5, borderBottomWidth: 1, borderBottomColor: '#E5E7EB', paddingBottom: 5 }}>
                 <Text style={{ fontSize: 12, fontWeight: 'bold', color: '#B91C1C' }}>CCP: {ccp.ccp_step}</Text>
                 <Text style={{ fontSize: 10, color: '#6B7280' }}>Hazard: {ccp.hazard}</Text>
              </View>
              
              <View style={{ flexDirection: 'row', marginTop: 5 }}>
                <View style={{ width: '33%', paddingRight: 5 }}>
                  <Text style={styles.subHeader}>Critical Limit</Text>
                  <Text style={styles.text}>{ccp.critical_limit}</Text>
                </View>
                <View style={{ width: '33%', paddingRight: 5 }}>
                  <Text style={styles.subHeader}>Monitoring</Text>
                  <Text style={styles.text}>{ccp.monitoring}</Text>
                </View>
                <View style={{ width: '33%' }}>
                  <Text style={styles.subHeader}>Corrective Action</Text>
                  <Text style={styles.text}>{ccp.corrective_action}</Text>
                </View>
              </View>
            </View>
          ))
        ) : (
          <View style={{ padding: 20, backgroundColor: '#F3F4F6', borderRadius: 4 }}>
            <Text style={{ textAlign: 'center', color: '#6B7280' }}>
              No Critical Control Points (CCPs) were identified in this process based on the input provided.
              However, strict adherence to Prerequisite Programs is required.
            </Text>
          </View>
        )}

        <Text style={styles.sectionTitle}>7. Validation & Verification</Text>
        <Text style={styles.text}>
          This plan must be validated before implementation to ensure it effectively controls hazards. 
          Ongoing verification activities (e.g., audits, sampling) should be conducted to confirm the plan is working.
        </Text>

        <Text style={styles.pageNumber} render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`} fixed />
        <Text style={styles.footer} fixed>Generated by ilovehaccp.com</Text>
      </Page>
    </Document>
  );
};

export default HACCPDocument;