export const legalTranslations = {
  en: {
    terms: {
      title: "Terms and Conditions",
      effective: "Effective: January 3, 2026",
      version: "Version 3.0",
      header_badge: "Legal Agreement",
      disclaimer: {
        title: "No Legal Advice & No Guarantee",
        intro: "The materials and HACCP plans generated by iLoveHACCP (\"the Service\") are for **informational and documentation purposes only**. The Service functions as a productivity tool to assist in the drafting of food safety documents based on user inputs and generic industry algorithms.",
        acknowledgement: "By using this Service, you expressly acknowledge that:",
        points: [
          "**Not a Certification:** The documents generated are **drafts**. They do not constitute a \"certificate,\" \"approval,\" or \"validation\" by any regulatory body (such as the FSA or local Environmental Health officers).",
          "**Regulatory Scope:** This tool uses logic guided by the principles of **EU Regulation (EC) No 852/2004** and applicable **UK retained food law**. It is **not** designed for compliance with non-EU/UK regulatory frameworks.",
          "**Operator Responsibility:** You, as the Food Business Operator, remain solely and legally responsible for the safety of your food, the accuracy of your HACCP plan, and its practical implementation. A document alone does not ensure safety.",
          "**Professional Review Required:** We strongly recommend (and in some high-risk cases, regulations may require) that your final plan be reviewed by a qualified local food safety consultant or environmental health officer to ensure it matches your specific on-site reality."
        ]
      },
      sections: [
        {
          title: "Agreement to Terms",
          content: "By accessing ilovehaccp.com (\"Website\", \"Service\"), you acknowledge that you have read, understood, and agree to be bound by these Terms and Conditions. These terms, along with our Privacy Statement and Cookie Policy, constitute a binding agreement between you and ilovehaccp.com.",
          summary: "By using our site, you agree to follow these rules."
        },
        {
          title: "Electronic Communication",
          content: "By using this Website or communicating with us by electronic means, you agree and acknowledge that we may communicate with you electronically on our website or by sending an email to you, and you agree that all agreements, notices, disclosures, and other communications that we provide to you electronically satisfy any legal requirement that such communications be in writing.",
          summary: "We will communicate via email and through the site, and that counts as 'in writing' legally."
        },
        {
          title: "Intellectual Property",
          content: "We or our licensors own and control all of the copyright and other intellectual property rights in the Website and the data, information, and other resources displayed by or accessible within the Website.\n\n**Limited License:** Unless specific content indicates otherwise, you are granted a limited, non-exclusive, non-sublicensable, and non-transferable license to use the resources solely for your personal or internal business purposes related to food safety management. You may not copy, reproduce, or commercialize the underlying software or proprietary models.",
          summary: "We own the technology. You get a license to use it for your business safety plans, but you can't sell our software as your own."
        },
        {
          title: "Nature of the Service",
          content: "The service is a software tool designed to assist users in drafting food safety documents. It is provided for informational purposes only and does not constitute a consulting engagement or professional advice.",
          summary: "We provide a tool to help you draft documents, not professional advice."
        },
        {
          title: "No Reliance / User Responsibility",
          content: "Users are solely responsible for the accuracy of their inputs and for the implementation and verification of any generated outputs within their business operations. The service provider does not assume responsibility for food safety outcomes.",
          summary: "You are responsible for your own data and food safety."
        },
        {
          title: "Automated Content Disclaimer",
          content: "Documentation is produced by automated systems and may contain assumptions or omissions. The service provider does not warrant that the content is accurate, complete, or suitable for any specific business environment or purpose.",
          summary: "Automated content may have errors. Check it carefully."
        },
        {
          title: "Paid Review Scope Limitation",
          content: "The human review is an advisory service based on user-provided data and does not include certification, technical validation, or representation before regulatory authorities. This review does not guarantee that the document will meet the expectations of any auditor or government agency.",
          summary: "Our review is advisory only and doesn't guarantee you'll pass an audit."
        },
        {
          title: "Limitation of Liability",
          content: "To the maximum extent permitted by law, the service provider shall not be held liable for any direct or indirect losses, damages, or regulatory penalties arising from the use of the service or reliance on its outputs.",
          summary: "We aren't liable for losses or penalties if you use our service."
        },
        {
          title: "Language",
          content: "These Terms and Conditions will be interpreted and construed exclusively in English, Portuguese, Spanish, and French. All notices and correspondence will be written exclusively in those languages. **In case of discrepancies, the English version prevails.**",
          summary: "We operate in 4 main languages. English version is the legal authority."
        }
      ]
    },
    privacy: {
      title: "Privacy Policy",
      effective: "Effective: January 3, 2026",
      version: "Version 2.0",
      header_badge: "Data Protection",
      intro: {
        title: "🔒 Our Core Privacy Promise: No Model Training",
        content: "We know your recipes and processes are your trade secrets. **We strictly do NOT use your specific proprietary data to train, fine-tune, or improve our public proprietary models.** Your data is isolated and used solely to generate your requested documents."
      },
      sections: [
        {
          title: "Data We Collect",
          content: "We collect two types of information:\n\n* **Account Data:** Name, email, and billing history (handled via Stripe). We do not store credit card numbers.\n* **Operational Data:** The specific inputs you provide to the HACCP builder (ingredients, equipment, staff names, process flows).",
          summary: "We collect your login info and the stuff you type into the builder. That's it."
        },
        {
          title: "How We Use Your Data",
          content: "Your data is used for one primary purpose: **to provide the Service.** This includes:\n\n* Generating your HACCP plan via our technology providers (Groq/OpenAI).\n* Sending you transactional emails (receipts, password resets).\n* Improving the UX of the platform (analytics on *how* features are used, not *what* is written).",
          summary: "We use your data to build your plan and keep the lights on. We don't sell it."
        },
        {
          title: "Technology & Third-Party Processing",
          content: "To generate your HACCP plans, we securely transmit limited text prompts to our data processing partners. We currently utilize:\n\n* **Groq Inc.:** For high-speed inference.\n* **OpenAI:** For advanced reasoning tasks. Data is processed via their API Platform which is distinct from ChatGPT and does not use data for training.\n\n**Zero-Training Guarantee:** Both partners are contractually prohibited from using data sent via our API integrations for model training or improvement. Your operational secrets remain yours.",
          summary: "We use Groq and OpenAI to process your data. They are under strict contract NOT to learn from your inputs."
        },
        {
          title: "Data Retention Policy",
          content: "We retain your personal information and generated plans for as long as your account is active or as needed to provide you the Service.\n\n* **Active Accounts:** Plans are stored indefinitely to allow for editing and re-downloading.\n* **Deleted Accounts:** Upon request, your account data is logically deleted immediately and permanently purged from our backups within 30 days.\n* **Inactive Accounts:** Accounts inactive for over 24 months may be subject to automated deletion after email notification.",
          summary: "We keep your plans while you need them. If you delete your account, they're gone from our servers within 30 days."
        }
      ]
    },
    cookies: {
      title: "Cookie Policy",
      effective: "Effective: January 3, 2026",
      version: "Version 2.0",
      header_badge: "Data Protection",
      intro: {
        title: "🍪 Our \"No-Nonsense\" Approach",
        content: "We hate cookie banners as much as you do. **We do not use invasive tracking pixels (like Facebook Pixel) or sell your browsing history to ad networks.** We only use cookies that are strictly necessary to make the app work and to understand basic usage patterns anonymously."
      },
      sections: [
        {
          title: "What Are Cookies?",
          content: "Cookies are tiny text files stored on your device when you visit a website. They act like a \"memory\" for the site, helping it recognize you when you come back or keeping you logged in as you navigate between pages. We also use **Local Storage**, which is a modern version of cookies that allows us to save your unfinished HACCP plan directly on your device so you don't lose your work.",
          summary: "Tiny files that help the website remember who you are and save your work."
        },
        {
          title: "Strictly Essential Cookies",
          content: "These are required for the website to function. You cannot switch these off in our systems.\n\n* **Authentication (`sb-access-token`):** Keeps you securely logged in via Supabase.\n* **Wizard State (`haccp_builder_state`):** Saves your progress in the form so you can refresh the page without starting over.\n* **Security (`csrf-token`):** Protects your account from malicious attacks (Cross-Site Request Forgery).\n* **Payments (`stripe.com`):** Used by our payment processor to securely handle transactions.",
          summary: "The bare minimum needed to log in, pay, and build your plan."
        },
        {
          title: "Performance & Analytics (Optional)",
          content: "With your consent, we use privacy-focused analytics tools (such as PostHog) to understand how our website is used. We track metrics like:\n\n* Which articles are most read?\n* How long does it take to complete the wizard?\n* Are users encountering errors on mobile devices?\n\n**This data is aggregated and anonymized.** These cookies are not set unless you accept them via our cookie banner.",
          summary: "We check broad trends to fix bugs, but only if you say yes."
        },
        {
          title: "Managing Cookies",
          content: "Most web browsers allow you to control cookies through their settings preferences. However, if you limit the ability of websites to set cookies, you may worsen your overall user experience, since it will no longer be personalized to you. It may also stop you from saving customized settings like login information.",
          summary: "You can block cookies in your browser, but the website might break (e.g., you won't stay logged in)."
        }
      ]
    },
    refund: {
      title: "Refund Policy",
      effective: "Effective: January 3, 2026",
      header_badge: "Billing",
      intro: {
        title: "💳 The Short Version",
        content: "Because our HACCP plans are digital products delivered instantly, **all sales are final and non-refundable** once the document has been generated or downloaded. Please review your free draft carefully before purchasing the final export."
      },
      sections: [
        {
          title: "Digital Goods Policy",
          content: "ilovehaccp.com sells \"intangible irrevocable goods\". Unlike a physical shirt you can return, a digital file cannot be \"returned\" once you have it. Therefore, we do not issue refunds for \"change of mind\" or \"not liking the layout\" after the purchase is complete.",
          summary: "Once you download it, you have it forever. We can't 'take it back', so we don't refund it."
        },
        {
          title: "When We DO Offer Refunds",
          content: "We stand by our technology. We **will** issue a refund if:\n\n* **Technical Failure:** The file was corrupted, blank, or technically unusable, and our support team was unable to resolve the issue after reasonable troubleshooting.\n* **Double Charge:** You were accidentally charged twice for the same transaction.\n* **Non-Delivery:** You paid but the system never unlocked the feature (and support couldn't fix it).",
          summary: "If our software breaks and we can't fix it, you get your money back. Period."
        },
        {
          title: "Disputes & Chargebacks",
          content: "We encourage you to contact us at support@ilovehaccp.com before initiating a dispute with your bank. We are reasonable people. However, if you file a fraudulent chargeback (claiming \"unauthorized\" for a valid purchase), we reserve the right to ban your account and dispute the claim with evidence of your IP and download logs.",
          summary: "Talk to us first. We want to help."
        }
      ]
    }
  }
};
