export const legalTranslations = {
  en: {
    terms: {
      title: "Terms and Conditions",
      effective: "Effective: January 3, 2026",
      version: "Version 3.0",
      header_badge: "Legal Agreement",
      disclaimer: {
        title: "No Legal Advice & No Guarantee",
        intro: "The materials and HACCP plans generated by iLoveHACCP (\"the Service\") are for **informational and documentation purposes only**. The Service functions as a productivity tool to assist in the drafting of food safety documents based on user inputs and generic industry algorithms.",
        acknowledgement: "By using this Service, you expressly acknowledge that:",
        points: [
          "**Not a Certification:** The documents generated are **drafts**. They do not constitute a \"certificate,\" \"approval,\" or \"validation\" by any regulatory body (such as the FSA, FDA, or local Environmental Health officers).",
          "**Regulatory Scope:** This tool uses logic guided by the principles of **EU Regulation (EC) No 852/2004** and applicable **UK retained food law**. It is **not** designed for compliance with United States FDA FSMA, USDA, or other non-EU/UK frameworks.",
          "**Operator Responsibility:** You, as the Food Business Operator, remain solely and legally responsible for the safety of your food, the accuracy of your HACCP plan, and its practical implementation. A document alone does not ensure safety.",
          "**Professional Review Required:** We strongly recommend (and in some high-risk cases, regulations may require) that your final plan be reviewed by a qualified local food safety consultant or environmental health officer to ensure it matches your specific on-site reality."
        ]
      },
      sections: [
        {
          title: "Agreement to Terms",
          content: "By accessing ilovehaccp.com (\"Website\", \"Service\"), you acknowledge that you have read, understood, and agree to be bound by these Terms and Conditions. These terms, along with our Privacy Statement and Cookie Policy, constitute a binding agreement between you and ilovehaccp.com.",
          summary: "By using our site, you agree to follow these rules."
        },
        {
          title: "Electronic Communication",
          content: "By using this Website or communicating with us by electronic means, you agree and acknowledge that we may communicate with you electronically on our website or by sending an email to you, and you agree that all agreements, notices, disclosures, and other communications that we provide to you electronically satisfy any legal requirement that such communications be in writing.",
          summary: "We will communicate via email and through the site, and that counts as 'in writing' legally."
        },
        {
          title: "Intellectual Property",
          content: "We or our licensors own and control all of the copyright and other intellectual property rights in the Website and the data, information, and other resources displayed by or accessible within the Website.\n\n**Limited License:** Unless specific content indicates otherwise, you are granted a limited, non-exclusive, non-sublicensable, and non-transferable license to use the resources solely for your personal or internal business purposes related to food safety management. You may not copy, reproduce, or commercialize the underlying software or proprietary models.",
          summary: "We own the technology. You get a license to use it for your business safety plans, but you can't sell our software as your own."
        },
        {
          title: "Nature of the Service",
          content: "The service is a software tool designed to assist users in drafting food safety documents. It is provided for informational purposes only and does not constitute a consulting engagement or professional advice.",
          summary: "We provide a tool to help you draft documents, not professional advice."
        },
        {
          title: "No Reliance / User Responsibility",
          content: "Users are solely responsible for the accuracy of their inputs and for the implementation and verification of any generated outputs within their business operations. The service provider does not assume responsibility for food safety outcomes.",
          summary: "You are responsible for your own data and food safety."
        },
        {
          title: "AI-Generated Content Disclaimer",
          content: "Documentation is produced by automated systems and may contain assumptions or omissions. The service provider does not warrant that the content is accurate, complete, or suitable for any specific business environment or purpose.",
          summary: "Automated content may have errors. Check it carefully."
        },
        {
          title: "Paid Review Scope Limitation",
          content: "The human review is an advisory service based on user-provided data and does not include certification, technical validation, or representation before regulatory authorities. This review does not guarantee that the document will meet the expectations of any auditor or government agency.",
          summary: "Our review is advisory only and doesn't guarantee you'll pass an audit."
        },
        {
          title: "Limitation of Liability",
          content: "To the maximum extent permitted by law, the service provider shall not be held liable for any direct or indirect losses, damages, or regulatory penalties arising from the use of the service or reliance on its outputs.",
          summary: "We aren't liable for losses or penalties if you use our service."
        },
        {
          title: "Language",
          content: "These Terms and Conditions will be interpreted and construed exclusively in English, Portuguese, Spanish, and French. All notices and correspondence will be written exclusively in those languages. **In case of discrepancies, the English version prevails.**",
          summary: "We operate in 4 main languages. English version is the legal authority."
        }
      ]
    },
    privacy: {
      title: "Privacy Policy",
      effective: "Effective: January 3, 2026",
      version: "Version 2.0",
      header_badge: "Data Protection",
      intro: {
        title: "🔒 Our Core Privacy Promise: No Model Training",
        content: "We know your recipes and processes are your trade secrets. **We strictly do NOT use your specific proprietary data to train, fine-tune, or improve our public proprietary models.** Your data is isolated and used solely to generate your requested documents."
      },
      sections: [
        {
          title: "Data We Collect",
          content: "We collect two types of information:\n\n* **Account Data:** Name, email, and billing history (handled via Stripe). We do not store credit card numbers.\n* **Operational Data:** The specific inputs you provide to the HACCP builder (ingredients, equipment, staff names, process flows).",
          summary: "We collect your login info and the stuff you type into the builder. That's it."
        },
        {
          title: "How We Use Your Data",
          content: "Your data is used for one primary purpose: **to provide the Service.** This includes:\n\n* Generating your HACCP plan via our technology providers (Groq/OpenAI).\n* Sending you transactional emails (receipts, password resets).\n* Improving the UX of the platform (analytics on *how* features are used, not *what* is written).",
          summary: "We use your data to build your plan and keep the lights on. We don't sell it."
        },
        {
          title: "Technology & Third-Party Processing",
          content: "To generate your HACCP plans, we securely transmit limited text prompts to our data processing partners. We currently utilize:\n\n* **Groq Inc.:** For high-speed inference.\n* **OpenAI:** For advanced reasoning tasks. Data is processed via their API Platform which is distinct from ChatGPT and does not use data for training.\n\n**Zero-Training Guarantee:** Both partners are contractually prohibited from using data sent via our API integrations for model training or improvement. Your operational secrets remain yours.",
          summary: "We use Groq and OpenAI to process your data. They are under strict contract NOT to learn from your inputs."
        },
        {
          title: "Data Retention Policy",
          content: "We retain your personal information and generated plans for as long as your account is active or as needed to provide you the Service.\n\n* **Active Accounts:** Plans are stored indefinitely to allow for editing and re-downloading.\n* **Deleted Accounts:** Upon request, your account data is logically deleted immediately and permanently purged from our backups within 30 days.\n* **Inactive Accounts:** Accounts inactive for over 24 months may be subject to automated deletion after email notification.",
          summary: "We keep your plans while you need them. If you delete your account, they're gone from our servers within 30 days."
        }
      ]
    },
    cookies: {
      title: "Cookie Policy",
      effective: "Effective: January 3, 2026",
      version: "Version 2.0",
      header_badge: "Data Protection",
      intro: {
        title: "🍪 Our \"No-Nonsense\" Approach",
        content: "We hate cookie banners as much as you do. **We do not use invasive tracking pixels (like Facebook Pixel) or sell your browsing history to ad networks.** We only use cookies that are strictly necessary to make the app work and to understand basic usage patterns anonymously."
      },
      sections: [
        {
          title: "What Are Cookies?",
          content: "Cookies are tiny text files stored on your device when you visit a website. They act like a \"memory\" for the site, helping it recognize you when you come back or keeping you logged in as you navigate between pages. We also use **Local Storage**, which is a modern version of cookies that allows us to save your unfinished HACCP plan directly on your device so you don't lose your work.",
          summary: "Tiny files that help the website remember who you are and save your work."
        },
        {
          title: "Strictly Essential Cookies",
          content: "These are required for the website to function. You cannot switch these off in our systems.\n\n* **Authentication (`sb-access-token`):** Keeps you securely logged in via Supabase.\n* **Wizard State (`haccp_builder_state`):** Saves your progress in the form so you can refresh the page without starting over.\n* **Security (`csrf-token`):** Protects your account from malicious attacks (Cross-Site Request Forgery).\n* **Payments (`stripe.com`):** Used by our payment processor to securely handle transactions.",
          summary: "The bare minimum needed to log in, pay, and build your plan."
        },
        {
          title: "Performance & Analytics (Optional)",
          content: "With your consent, we use privacy-focused analytics tools (such as PostHog) to understand how our website is used. We track metrics like:\n\n* Which articles are most read?\n* How long does it take to complete the wizard?\n* Are users encountering errors on mobile devices?\n\n**This data is aggregated and anonymized.** These cookies are not set unless you accept them via our cookie banner.",
          summary: "We check broad trends to fix bugs, but only if you say yes."
        },
        {
          title: "Managing Cookies",
          content: "Most web browsers allow you to control cookies through their settings preferences. However, if you limit the ability of websites to set cookies, you may worsen your overall user experience, since it will no longer be personalized to you. It may also stop you from saving customized settings like login information.",
          summary: "You can block cookies in your browser, but the website might break (e.g., you won't stay logged in)."
        }
      ]
    },
    refund: {
      title: "Refund Policy",
      effective: "Effective: January 3, 2026",
      header_badge: "Billing",
      intro: {
        title: "💳 The Short Version",
        content: "Because our HACCP plans are digital products delivered instantly, **all sales are final and non-refundable** once the document has been generated or downloaded. Please review your free draft carefully before purchasing the final export."
      },
      sections: [
        {
          title: "Digital Goods Policy",
          content: "ilovehaccp.com sells \"intangible irrevocable goods\". Unlike a physical shirt you can return, a digital file cannot be \"returned\" once you have it. Therefore, we do not issue refunds for \"change of mind\" or \"not liking the layout\" after the purchase is complete.",
          summary: "Once you download it, you have it forever. We can't 'take it back', so we don't refund it."
        },
        {
          title: "When We DO Offer Refunds",
          content: "We stand by our technology. We **will** issue a refund if:\n\n* **Technical Failure:** The file was corrupted, blank, or technically unusable, and our support team could not fix it within 48 hours.\n* **Double Charge:** You were accidentally charged twice for the same transaction.\n* **Non-Delivery:** You paid but the system never unlocked the feature (and support couldn't fix it).",
          summary: "If our software breaks and we can't fix it, you get your money back. Period."
        },
        {
          title: "Disputes & Chargebacks",
          content: "We encourage you to contact us at support@ilovehaccp.com before initiating a dispute with your bank. We are reasonable people. However, if you file a fraudulent chargeback (claiming \"unauthorized\" for a valid purchase), we reserve the right to ban your account and dispute the claim with evidence of your IP and download logs.",
          summary: "Talk to us first. We want to help."
        }
      ]
    }
  },
  pt: {
    terms: {
      title: "Termos e Condições",
      effective: "Efetivo: 3 de Janeiro de 2026",
      version: "Versão 3.0",
      header_badge: "Acordo Legal",
      disclaimer: {
        title: "Sem Aconselhamento Legal & Sem Garantia",
        intro: "Os materiais e planos HACCP gerados pelo iLoveHACCP (\"o Serviço\") destinam-se apenas a **fins informativos e de documentação**. O Serviço funciona como uma ferramenta de produtividade para auxiliar na redação de documentos de segurança alimentar com base nas entradas do utilizador e algoritmos genéricos da indústria.",
        acknowledgement: "Ao utilizar este Serviço, reconhece expressamente que:",
        points: [
          "**Não é uma Certificação:** Os documentos gerados são **rascunhos**. Não constituem um \"certificado\", \"aprovação\" ou \"validação\" por qualquer organismo regulador (como a ASAE, DGAV ou autoridades locais).",
          "**Âmbito Regulamentar:** Esta ferramenta utiliza lógica guiada pelos princípios do **Regulamento (CE) N.º 852/2004 da UE** e legislação alimentar aplicável. **Não** foi concebida para conformidade com a FDA FSMA dos EUA ou outros quadros não-UE.",
          "**Responsabilidade do Operador:** Você, como Operador da Empresa do Setor Alimentar, permanece única e legalmente responsável pela segurança dos seus alimentos, pela precisão do seu plano HACCP e pela sua implementação prática. Um documento por si só não garante a segurança.",
          "**Revisão Profissional Necessária:** Recomendamos vivamente (e em alguns casos de alto risco, os regulamentos podem exigir) que o seu plano final seja revisto por um consultor de segurança alimentar qualificado ou autoridade de saúde para garantir que corresponde à sua realidade local."
        ]
      },
      sections: [
        {
          title: "Acordo com os Termos",
          content: "Ao aceder a ilovehaccp.com (\"Website\", \"Serviço\"), reconhece que leu, compreendeu e concorda em ficar vinculado a estes Termos e Condições. Estes termos, juntamente com a nossa Declaração de Privacidade e Política de Cookies, constituem um acordo vinculativo entre si e ilovehaccp.com.",
          summary: "Ao usar o nosso site, concorda em seguir estas regras."
        },
        {
          title: "Comunicação Eletrónica",
          content: "Ao utilizar este Website ou comunicar connosco por meios eletrónicos, concorda e reconhece que podemos comunicar consigo eletronicamente no nosso website ou enviando-lhe um e-mail, e concorda que todos os acordos, avisos, divulgações e outras comunicações que lhe fornecemos eletronicamente satisfazem qualquer requisito legal de que tais comunicações sejam por escrito.",
          summary: "Comunicaremos por e-mail e através do site, e isso conta como 'por escrito' legalmente."
        },
        {
          title: "Propriedade Intelectual",
          content: "Nós ou os nossos licenciadores detemos e controlamos todos os direitos de autor e outros direitos de propriedade intelectual no Website e nos dados, informações e outros recursos exibidos ou acessíveis no Website.\n\n**Licença Limitada:** Salvo indicação em contrário no conteúdo específico, é-lhe concedida uma licença limitada, não exclusiva, não sublicenciável e intransferível para utilizar os recursos apenas para os seus fins pessoais ou comerciais internos relacionados com a gestão da segurança alimentar. Não pode copiar, reproduzir ou comercializar o software subjacente ou modelos proprietários.",
          summary: "Somos donos da tecnologia. Obtém uma licença para a usar nos seus planos de segurança, mas não pode vender o nosso software."
        },
        {
          title: "Sem Garantia de Conformidade",
          content: "**O iLoveHACCP não garante que qualquer plano gerado pelo Serviço seja aceite pela sua autoridade local.** Os regulamentos de segurança alimentar (incluindo CE 852/2004) estão sujeitos à interpretação de inspetores individuais. O Serviço fornece uma estrutura baseada em princípios gerais. **Não** é um sistema \"aprovado\" ou \"certificado\". A falha em passar numa auditoria ou inspeção é da exclusiva responsabilidade do Utilizador.",
          summary: "Nós fornecemos a ferramenta, você fornece a conformidade. Passar na inspeção é 100% trabalho seu."
        },
        {
          title: "Isenção de Responsabilidade de Segurança Alimentar",
          content: "ilovehaccp.com e os seus operadores não serão responsáveis por qualquer doença transmitida por alimentos, lesão, morte, reação alérgica ou incidente de saúde pública resultante do consumo de produtos produzidos pela sua empresa. A utilização do nosso software é apenas um auxílio à documentação e não substitui a gestão ativa da segurança alimentar, monitorização diária, formação de pessoal ou manutenção de equipamentos. Reconhece que é o único responsável pela segurança dos alimentos que produz.",
          summary: "Se alguém ficar doente com a sua comida, não pode culpar o nosso software."
        },
        {
          title: "Idioma",
          content: "Estes Termos e Condições serão interpretados e construídos exclusivamente em Inglês, Português, Espanhol e Francês. Todos os avisos e correspondência serão escritos exclusivamente nessas línguas. **Em caso de discrepâncias, a versão em Inglês prevalece.**",
          summary: "Operamos em 4 línguas principais. A versão em Inglês é a autoridade legal."
        }
      ]
    },
    cookies: {
      title: "Política de Cookies",
      effective: "Efetivo: 3 de Janeiro de 2026",
      version: "Versão 2.0",
      header_badge: "Proteção de Dados",
      intro: {
        title: "🍪 A Nossa Abordagem \"Sem Complicações\"",
        content: "Nós odiamos banners de cookies tanto quanto você. **Não usamos pixels de rastreamento invasivos (como o Facebook Pixel) nem vendemos o seu histórico de navegação a redes de publicidade.** Usamos apenas cookies que são estritamente necessários para fazer a aplicação funcionar e para entender os padrões básicos de utilização de forma anónima."
      },
      sections: [
        {
          title: "O Que São Cookies?",
          content: "Cookies são pequenos ficheiros de texto armazenados no seu dispositivo quando visita um website. Agem como uma \"memória\" para o site, ajudando-o a reconhecê-lo quando volta ou mantendo-o ligado enquanto navega entre páginas. Também usamos **Local Storage**, que é uma versão moderna de cookies que nos permite guardar o seu plano HACCP não finalizado diretamente no seu dispositivo para que não perca o seu trabalho.",
          summary: "Pequenos ficheiros que ajudam o site a lembrar quem é e a guardar o seu trabalho."
        },
        {
          title: "Cookies Estritamente Essenciais",
          content: "Estes são necessários para o funcionamento do website. Não pode desativá-los nos nossos sistemas.\n\n* **Autenticação (`sb-access-token`):** Mantém-no ligado de forma segura via Supabase.\n* **Estado do Assistente (`haccp_builder_state`):** Guarda o seu progresso no formulário para que possa atualizar a página sem recomeçar.\n* **Segurança (`csrf-token`):** Protege a sua conta contra ataques maliciosos (Cross-Site Request Forgery).\n* **Pagamentos (`stripe.com`):** Usado pelo nosso processador de pagamentos para lidar com transações de forma segura.",
          summary: "O mínimo indispensável necessário para entrar, pagar e construir o seu plano."
        },
        {
          title: "Desempenho & Análise (Opcional)",
          content: "Com o seu consentimento, usamos ferramentas de análise focadas na privacidade (como o PostHog) para entender como o nosso website é utilizado. Rastreamos métricas como:\n\n* Que artigos são mais lidos?\n* Quanto tempo demora a completar o assistente?\n* Os utilizadores estão a encontrar erros em dispositivos móveis?\n\n**Estes dados são agregados e anonimizados.** Estes cookies não são definidos a menos que os aceite através do nosso banner de cookies.",
          summary: "Verificamos tendências gerais para corrigir erros, mas apenas se disser que sim."
        },
        {
          title: "Gerir Cookies",
          content: "A maioria dos navegadores web permite controlar cookies através das suas preferências de definições. No entanto, se limitar a capacidade dos websites de definir cookies, poderá piorar a sua experiência geral de utilizador, uma vez que deixará de ser personalizada para si. Também poderá impedi-lo de guardar definições personalizadas, como informações de login.",
          summary: "Pode bloquear cookies no seu navegador, mas o site pode deixar de funcionar corretamente."
        }
      ]
    },
    refund: {
      title: "Política de Reembolso",
      effective: "Efetivo: 3 de Janeiro de 2026",
      header_badge: "Faturação",
      intro: {
        title: "💳 A Versão Curta",
        content: "Porque os nossos planos HACCP são produtos digitais entregues instantaneamente, **todas as vendas são finais e não reembolsáveis** uma vez que o documento tenha sido gerado ou descarregado. Por favor, reveja o seu rascunho gratuito cuidadosamente antes de comprar a exportação final."
      },
      sections: [
        {
          title: "Política de Bens Digitais",
          content: "ilovehaccp.com vende \"bens irrevogáveis intangíveis\". Ao contrário de uma camisa física que pode devolver, um ficheiro digital não pode ser \"devolvido\" uma vez que o tenha. Portanto, não emitimos reembolsos por \"mudança de ideias\" ou \"não gostar do layout\" após a conclusão da compra.",
          summary: "Uma vez descarregado, tem-no para sempre. Não podemos 'recebê-lo de volta', por isso não o reembolsamos."
        },
        {
          title: "Quando OFERECEMOS Reembolsos",
          content: "Nós garantimos a nossa tecnologia. **Emitiremos** um reembolso se:\n\n* **Falha Técnica:** O ficheiro estava corrompido, em branco ou tecnicamente inutilizável, e a nossa equipa de suporte não conseguiu corrigi-lo dentro de 48 horas.\n* **Cobrança Dupla:** Foi acidentalmente cobrado duas vezes pela mesma transação.\n* **Não Entrega:** Pagou, mas o sistema nunca desbloqueou a funcionalidade (e o suporte não conseguiu corrigir).",
          summary: "Se o nosso software falhar e não conseguirmos corrigir, recebe o seu dinheiro de volta. Ponto final."
        },
        {
          title: "Disputas & Chargebacks",
          content: "Encorajamo-lo a contactar-nos em support@ilovehaccp.com antes de iniciar uma disputa com o seu banco. Somos pessoas razoáveis. No entanto, se apresentar um chargeback fraudulento (alegando \"não autorizado\" para uma compra válida), reservamo-nos o direito de banir a sua conta e contestar a reclamação com provas do seu IP e registos de download.",
          summary: "Fale connosco primeiro. Queremos ajudar."
        }
      ]
    }
  },
  es: {
    terms: {
      title: "Términos y Condiciones",
      effective: "Vigente: 3 de enero de 2026",
      version: "Versión 3.0",
      header_badge: "Acuerdo Legal",
      disclaimer: {
        title: "Sin Asesoramiento Legal y Sin Garantía",
        intro: "Los materiales y planes HACCP generados por iLoveHACCP (\"el Servicio\") son solo para **fines informativos y de documentación**. El Servicio funciona como una herramienta de productividad.",
        acknowledgement: "Al utilizar este Servicio, usted reconoce expresamente que:",
        points: [
          "**No es una Certificación:** Los documentos generados son **borradores**. No constituyen un \"certificado\", \"aprobación\" o \"validación\" por ningún organismo regulador.",
          "**Alcance Regulatorio:** Esta herramienta utiliza lógica guiada por los principios del **Reglamento (CE) Nº 852/2004 de la UE**.",
          "**Responsabilidad del Operador:** Usted sigue siendo el único responsable legal de la seguridad de sus alimentos y la precisión de su plan HACCP.",
          "**Revisión Profesional Requerida:** Recomendamos encarecidamente que su plan final sea revisado por un consultor calificado."
        ]
      },
      sections: [
        {
          title: "Acuerdo con los Términos",
          content: "Al acceder a ilovehaccp.com, usted acepta estar sujeto a estos Términos y Condiciones.",
          summary: "Al usar nuestro sitio, acepta seguir estas reglas."
        },
        {
          title: "Sin Garantía de Cumplimiento",
          content: "**iLoveHACCP no garantiza que ningún plan generado por el Servicio sea aceptado por su autoridad local.** El Servicio proporciona una estructura basada en principios generales. **No** es un sistema \"aprobado\" o \"certificado\".",
          summary: "Proporcionamos la herramienta, usted proporciona el cumplimiento."
        },
        {
          title: "Exención de Responsabilidad",
          content: "El uso de nuestro software es solo una ayuda para la documentación y no sustituye la gestión activa de la seguridad alimentaria. Usted reconoce que es el único responsable de la seguridad de los alimentos que produce.",
          summary: "Si alguien se enferma con su comida, no puede culpar a nuestro software."
        },
        {
          title: "Idioma",
          content: "Estos Términos y Condiciones se interpretarán exclusivamente en inglés, portugués, español y francés. **En caso de discrepancia, prevalecerá la versión en inglés.**",
          summary: "La versión en inglés es la autoridad legal."
        }
      ]
    },
    privacy: {
      title: "Política de Privacidad",
      effective: "Vigente: 3 de enero de 2026",
      version: "Versión 2.0",
      header_badge: "Protección de Datos",
      intro: {
        title: "🔒 Nuestra Promesa de Privacidad",
        content: "**Estrictamente NO utilizamos sus datos propietarios específicos para entrenar, ajustar o mejorar nuestros modelos públicos.** Sus datos están aislados."
      },
      sections: [
        {
          title: "Datos que Recopilamos",
          content: "Recopilamos Datos de Cuenta (Nombre, correo) y Datos Operativos (entradas del constructor HACCP).",
          summary: "Solo lo necesario para crear la cuenta y el plan."
        }
      ]
    },
    cookies: {
      title: "Política de Cookies",
      effective: "Vigente: 3 de enero de 2026",
      version: "Versión 2.0",
      header_badge: "Protección de Datos",
      intro: {
        title: "🍪 Nuestro Enfoque",
        content: "Solo utilizamos cookies estrictamente necesarias y analíticas anónimas (con consentimiento)."
      },
      sections: [
        {
          title: "Cookies Estrictamente Esenciales",
          content: "Necesarias para inicio de sesión, seguridad y pagos. No se pueden desactivar.",
          summary: "Esenciales para que el sitio funcione."
        }
      ]
    },
    refund: {
      title: "Política de Reembolso",
      effective: "Vigente: 3 de enero de 2026",
      header_badge: "Facturación",
      intro: {
        title: "💳 La Versión Corta",
        content: "Debido a que nuestros planes HACCP son productos digitales, **todas las ventas son finales y no reembolsables** después de la descarga."
      },
      sections: [
        {
          title: "Política de Bienes Digitales",
          content: "Los archivos digitales no se pueden \"devolver\". No emitimos reembolsos por \"cambio de opinión\".",
          summary: "Una vez descargado, es suyo."
        }
      ]
    }
  },
  fr: {
    terms: {
      title: "Conditions Générales",
      effective: "Effectif : 3 janvier 2026",
      version: "Version 3.0",
      header_badge: "Accord Légal",
      disclaimer: {
        title: "Pas de Conseil Juridique & Pas de Garantie",
        intro: "Les matériaux et plans HACCP générés par iLoveHACCP (\"le Service\") sont uniquement à des **fins d'information et de documentation**. Le Service fonctionne comme un outil de productivité.",
        acknowledgement: "En utilisant ce Service, vous reconnaissez expressément que :",
        points: [
          "**Pas une Certification :** Les documents générés sont des **brouillons**. Ils ne constituent pas un \"certificat\", une \"approbation\" ou une \"validation\" par un organisme de réglementation.",
          "**Portée Réglementaire :** Cet outil utilise une logique guidée par les principes du **Règlement (CE) N° 852/2004 de l'UE**.",
          "**Responsabilité de l'Opérateur :** Vous restez seul et légalement responsable de la sécurité de vos aliments et de l'exactitude de votre plan HACCP.",
          "**Examen Professionnel Requis :** Nous recommandons vivement que votre plan final soit examiné par un consultant qualifié."
        ]
      },
      sections: [
        {
          title: "Accord aux Conditions",
          content: "En accédant à ilovehaccp.com, vous acceptez d'être lié par ces Conditions Générales.",
          summary: "En utilisant notre site, vous acceptez de suivre ces règles."
        },
        {
          title: "Pas de Garantie de Conformité",
          content: "**iLoveHACCP ne garantit pas qu'un plan généré par le Service sera accepté par votre autorité locale.** Le Service fournit une structure basée sur des principes généraux. Ce n'est **pas** un système \"approuvé\" ou \"certifié\".",
          summary: "Nous fournissons l'outil, vous fournissez la conformité."
        },
        {
          title: "Exonération de Responsabilité",
          content: "L'utilisation de notre logiciel n'est qu'une aide à la documentation et ne remplace pas la gestion active de la sécurité alimentaire. Vous reconnaissez que vous êtes seul responsable de la sécurité des aliments que vous produisez.",
          summary: "Si quelqu'un tombe malade à cause de votre nourriture, vous ne pouvez pas blâmer notre logiciel."
        },
        {
          title: "Langue",
          content: "Ces Conditions Générales seront interprétées exclusivement en anglais, portugais, espagnol et français. **En cas de divergence, la version anglaise prévaudra.**",
          summary: "La version anglaise est l'autorité légale."
        }
      ]
    },
    privacy: {
      title: "Politique de Confidentialité",
      effective: "Effectif : 3 janvier 2026",
      version: "Version 2.0",
      header_badge: "Protection des Données",
      intro: {
        title: "🔒 Notre Promesse de Confidentialité",
        content: "**Nous n'utilisons strictement PAS vos données propriétaires spécifiques pour entraîner, affiner ou améliorer nos modèles publics.** Vos données sont isolées."
      },
      sections: [
        {
          title: "Données que Nous Collectons",
          content: "Nous collectons des Données de Compte (Nom, email) et des Données Opérationnelles (entrées du HACCP builder).",
          summary: "Seulement ce qui est nécessaire pour créer le compte et le plan."
        }
      ]
    },
    cookies: {
      title: "Politique relative aux Cookies",
      effective: "Effectif : 3 janvier 2026",
      version: "Version 2.0",
      header_badge: "Protection des Données",
      intro: {
        title: "🍪 Notre Approche",
        content: "Nous utilisons uniquement des cookies strictement nécessaires et analytiques anonymes (avec consentement)."
      },
      sections: [
        {
          title: "Cookies Strictement Essentiels",
          content: "Nécessaires pour la connexion, la sécurité et les paiements. Ne peuvent pas être désactivés.",
          summary: "Essentiels pour que le site fonctionne."
        }
      ]
    },
    refund: {
      title: "Politique de Remboursement",
      effective: "Effectif : 3 janvier 2026",
      header_badge: "Facturation",
      intro: {
        title: "💳 La Version Courte",
        content: "Comme nos plans HACCP sont des produits numériques, **toutes les ventes sont finales et non remboursables** après téléchargement."
      },
      sections: [
        {
          title: "Politique des Biens Numériques",
          content: "Les fichiers numériques ne peuvent pas être \"retournés\". Nous n'émettons pas de remboursement pour \"changement d'avis\".",
          summary: "Une fois téléchargé, il est à vous."
        }
      ]
    }
  }
};