export type Language = 'en' | 'es' | 'fr' | 'pt';

export const translations = {
  en: {
    nav: {
      builder: "Builder",
      features: "Features",
      resources: "Resources",
      pricing: "Pricing",
      about: "About",
      contact: "Contact",
      login: "Log In",
      getStarted: "Get Started"
    },
    hero: {
      title: "HACCP Plans Done in Minutes.",
      subtitle: "Stop wrestling with Word documents. Our AI consultant generates audit-ready food safety plans tailored to your menu.",
      cta: "Build Your Plan Free"
    },
    wizard: {
      title: "Let's Build Your HACCP Plan",
      subtitle: "Answer a few questions and our AI will draft a complete, compliance-ready document.",
      start: "Start Builder",
      next: "Next",
      back: "Back",
      add: "Add",
      generating: "Crafting your HACCP plan...",
      generatingDesc: "Our AI is applying standards to your specific business context.",
      download: "Download PDF",
      success: "Your Draft is Ready!",
      step_business: "Business Context",
      step_products: "Product Details",
    },
    pdf: {
      title: "HACCP Plan",
      subtitle: "Food Safety Management System",
      facility: "Facility Name",
      product_scope: "Product Scope",
      date_issue: "Date of Issue",
      standard: "Standard",
      disclaimer: "This document is a generated draft and must be validated by a qualified professional.",
      confidential: "CONFIDENTIAL",
      version: "Version 1.0",
      generated_by: "Generated by ilovehaccp.com - AI Food Safety",
      
      // Sections
      s1_title: "1.0 Plan Overview",
      s1_executive: "1.1 Executive Summary",
      s1_product: "1.2 Product Description",
      s1_process: "1.3 Process Narrative",
      
      // Labels
      lbl_product_name: "Product Name",
      lbl_description: "Description",
      lbl_intended_use: "Intended Use",
      lbl_storage: "Storage",
      
      // S2 PRPs
      s2_title: "2.0 Prerequisite Programs (PRPs)",
      s2_desc: "Foundation programs in place to control general hygiene hazards.",
      col_program: "Program",
      col_details: "Details & Control",
      
      // S3 Hazards
      s3_title: "3.0 Hazard Analysis (Principle 1 & 2)",
      col_step: "Step",
      col_hazards: "Hazards (B/C/P)",
      col_control: "Control Measure",
      col_ccp: "CCP?",
      val_prerequisite: "Prerequisite",
      
      // S4 CCPs
      s4_title: "4.0 HACCP Control Chart (Principles 3-7)",
      s4_desc: "Detailed control plan for identified Critical Control Points.",
      lbl_hazard: "SIGNIFICANT HAZARD",
      lbl_critical_limit: "Critical Limit",
      lbl_monitoring: "Monitoring",
      lbl_corrective: "Corrective Action",
      msg_no_ccps: "No Critical Control Points (CCPs) identified. Process is controlled via PRPs.",
      
      // Signatures
      sign_prepared: "Prepared By (HACCP Team Leader)",
      sign_approved: "Approved By (Management)",
      
      // Toolkit
      tk_title: "Toolkit: Monitoring Logs",
      tk_temp_title: "Appendix A: Temperature Control Log",
      tk_temp_desc: "Use this log to record temperatures for Critical Control Points (e.g., Cooking, Chilled Storage).",
      col_date: "Date",
      col_time: "Time",
      col_item: "Item/Equipment",
      col_temp: "Temp (°C)",
      col_action: "Action",
      col_sign: "Sign",
      msg_corrective: "*Corrective Action Required if Critical Limits are breached. Record actions taken in the 'Action' column.",
      
      tk_clean_title: "Appendix B: Daily Cleaning Checklist",
      col_task: "Cleaning Task",
      days: { mon: "Mon", tue: "Tue", wed: "Wed", thu: "Thu", fri: "Fri", sat_sun: "Sat/Sun" },
      tasks: {
        surfaces: "Surfaces & Preparation Boards",
        cooking: "Cooking Equipment (Ovens/Stoves)",
        fridges: "Fridges & Handles",
        sinks: "Sinks & Taps",
        floors: "Floors & Drains",
        waste: "Waste Bins (Emptied & Cleaned)",
        handwash: "Staff Handwash Stations"
      },
      
      tk_train_title: "Appendix C: Staff Training Record",
      col_employee: "Employee Name",
      col_train_desc: "Training Description (e.g. HACCP Level 2)"
    }
  },
  es: {
    nav: {
      builder: "Constructor",
      features: "Características",
      resources: "Recursos",
      pricing: "Precios",
      about: "Sobre nosotros",
      contact: "Contacto",
      login: "Iniciar Sesión",
      getStarted: "Empezar"
    },
    hero: {
      title: "Planes HACCP en Minutos.",
      subtitle: "Deje de luchar con documentos de Word. Nuestra IA genera planes de seguridad alimentaria listos para auditoría.",
      cta: "Crear Plan Gratis"
    },
    wizard: {
      title: "Vamos a crear su plan HACCP",
      subtitle: "Responda unas preguntas y nuestra IA redactará un documento completo y listo para cumplir.",
      start: "Iniciar Constructor",
      next: "Siguiente",
      back: "Atrás",
      add: "Añadir",
      generating: "Creando su plan HACCP...",
      generatingDesc: "Nuestra IA está aplicando estándares a su contexto empresarial.",
      download: "Descargar PDF",
      success: "¡Su borrador está listo!",
      step_business: "Contexto Empresarial",
      step_products: "Detalles del Producto"
    },
    pdf: {
      title: "Plan HACCP",
      subtitle: "Sistema de Gestión de Seguridad Alimentaria",
      facility: "Nombre de la Instalación",
      product_scope: "Alcance del Producto",
      date_issue: "Fecha de Emisión",
      standard: "Estándar",
      disclaimer: "Este documento es un borrador generado y debe ser validado por un profesional calificado.",
      confidential: "CONFIDENCIAL",
      version: "Versión 1.0",
      generated_by: "Generado por ilovehaccp.com - Seguridad Alimentaria con IA",
      
      s1_title: "1.0 Resumen del Plan",
      s1_executive: "1.1 Resumen Ejecutivo",
      s1_product: "1.2 Descripción del Producto",
      s1_process: "1.3 Narrativa del Proceso",
      
      lbl_product_name: "Nombre del Producto",
      lbl_description: "Descripción",
      lbl_intended_use: "Uso Previsto",
      lbl_storage: "Almacenamiento",
      
      s2_title: "2.0 Programas de Prerrequisitos (PPR)",
      s2_desc: "Programas fundamentales para controlar peligros generales de higiene.",
      col_program: "Programa",
      col_details: "Detalles y Control",
      
      s3_title: "3.0 Análisis de Peligros (Principio 1 y 2)",
      col_step: "Paso",
      col_hazards: "Peligros (B/Q/F)",
      col_control: "Medida de Control",
      col_ccp: "¿PCC?",
      val_prerequisite: "Prerrequisito",
      
      s4_title: "4.0 Cuadro de Control HACCP (Principios 3-7)",
      s4_desc: "Plan de control detallado para los Puntos Críticos de Control identificados.",
      lbl_hazard: "PELIGRO SIGNIFICATIVO",
      lbl_critical_limit: "Límite Crítico",
      lbl_monitoring: "Monitoreo",
      lbl_corrective: "Acción Correctiva",
      msg_no_ccps: "No se identificaron Puntos Críticos de Control (PCC). El proceso se controla mediante PPR.",
      
      sign_prepared: "Preparado por (Líder del Equipo HACCP)",
      sign_approved: "Aprobado por (Gerencia)",
      
      tk_title: "Herramientas: Registros de Monitoreo",
      tk_temp_title: "Apéndice A: Registro de Control de Temperatura",
      tk_temp_desc: "Utilice este registro para PCC (ej. Cocción, Almacenamiento en Frío).",
      col_date: "Fecha",
      col_time: "Hora",
      col_item: "Ítem/Equipo",
      col_temp: "Temp (°C)",
      col_action: "Acción",
      col_sign: "Firma",
      msg_corrective: "*Acción Correctiva requerida si se violan los Límites Críticos.",
      
      tk_clean_title: "Apéndice B: Lista de Limpieza Diaria",
      col_task: "Tarea de Limpieza",
      days: { mon: "Lun", tue: "Mar", wed: "Mié", thu: "Jue", fri: "Vie", sat_sun: "Sáb/Dom" },
      tasks: {
        surfaces: "Superficies y Tablas de Preparación",
        cooking: "Equipos de Cocina (Hornos/Estufas)",
        fridges: "Refrigeradores y Manijas",
        sinks: "Fregaderos y Grifos",
        floors: "Pisos y Drenajes",
        waste: "Contenedores de Basura (Vaciados y Limpios)",
        handwash: "Estaciones de Lavado de Manos"
      },
      
      tk_train_title: "Apéndice C: Registro de Capacitación",
      col_employee: "Nombre del Empleado",
      col_train_desc: "Descripción de la Capacitación"
    }
  },
  fr: {
    nav: {
      builder: "Générateur",
      features: "Fonctionnalités",
      resources: "Ressources",
      pricing: "Tarifs",
      about: "À propos",
      contact: "Contact",
      login: "Connexion",
      getStarted: "Commencer"
    },
    hero: {
      title: "Plans HACCP en quelques minutes.",
      subtitle: "Arrêtez de lutter avec des documents Word. Notre IA génère des plans de sécurité alimentaire prêts pour l'audit.",
      cta: "Créer un plan gratuit"
    },
    wizard: {
      title: "Créons votre plan HACCP",
      subtitle: "Répondez à quelques questions et notre IA rédigera un document complet.",
      start: "Démarrer",
      next: "Suivant",
      back: "Retour",
      add: "Ajouter",
      generating: "Création de votre plan HACCP...",
      generatingDesc: "Notre IA applique les normes à votre contexte commercial.",
      download: "Télécharger PDF",
      success: "Votre brouillon est prêt !",
      step_business: "Contexte Commercial",
      step_products: "Détails du Produit"
    },
    pdf: {
      title: "Plan HACCP",
      subtitle: "Système de Gestion de la Sécurité Alimentaire",
      facility: "Nom de l'Établissement",
      product_scope: "Portée du Produit",
      date_issue: "Date d'Émission",
      standard: "Norme",
      disclaimer: "Ce document est un brouillon généré et doit être validé par un professionnel qualifié.",
      confidential: "CONFIDENTIEL",
      version: "Version 1.0",
      generated_by: "Généré par ilovehaccp.com - Sécurité Alimentaire IA",
      
      s1_title: "1.0 Aperçu du Plan",
      s1_executive: "1.1 Résumé Exécutif",
      s1_product: "1.2 Description du Produit",
      s1_process: "1.3 Description du Processus",
      
      lbl_product_name: "Nom du Produit",
      lbl_description: "Description",
      lbl_intended_use: "Utilisation Prévue",
      lbl_storage: "Stockage",
      
      s2_title: "2.0 Programmes Prérequis (PRP)",
      s2_desc: "Programmes fondamentaux pour contrôler les dangers d'hygiène généraux.",
      col_program: "Programme",
      col_details: "Détails et Contrôle",
      
      s3_title: "3.0 Analyse des Dangers (Principe 1 & 2)",
      col_step: "Étape",
      col_hazards: "Dangers (B/C/P)",
      col_control: "Mesure de Maîtrise",
      col_ccp: "CCP ?",
      val_prerequisite: "Prérequis",
      
      s4_title: "4.0 Tableau de Contrôle HACCP (Principes 3-7)",
      s4_desc: "Plan de contrôle détaillé pour les Points Critiques de Contrôle identifiés.",
      lbl_hazard: "DANGER SIGNIFICATIF",
      lbl_critical_limit: "Limite Critique",
      lbl_monitoring: "Surveillance",
      lbl_corrective: "Action Corrective",
      msg_no_ccps: "Aucun Point Critique de Contrôle (CCP) identifié. Le processus est contrôlé via les PRP.",
      
      sign_prepared: "Préparé par (Chef d'Équipe HACCP)",
      sign_approved: "Approuvé par (Direction)",
      
      tk_title: "Outils : Journaux de Surveillance",
      tk_temp_title: "Annexe A : Journal de Contrôle de Température",
      tk_temp_desc: "Utilisez ce journal pour les CCP (ex. Cuisson, Stockage au Froid).",
      col_date: "Date",
      col_time: "Heure",
      col_item: "Article/Équipement",
      col_temp: "Temp (°C)",
      col_action: "Action",
      col_sign: "Signe",
      msg_corrective: "*Action Corrective requise si les Limites Critiques sont dépassées.",
      
      tk_clean_title: "Annexe B : Liste de Nettoyage Quotidien",
      col_task: "Tâche de Nettoyage",
      days: { mon: "Lun", tue: "Mar", wed: "Mer", thu: "Jeu", fri: "Ven", sat_sun: "Sam/Dim" },
      tasks: {
        surfaces: "Surfaces et Planches de Préparation",
        cooking: "Équipement de Cuisson (Fours/Cuisinières)",
        fridges: "Réfrigérateurs et Poignées",
        sinks: "Éviers et Robinets",
        floors: "Sols et Drains",
        waste: "Poubelles (Vidées et Nettoyées)",
        handwash: "Stations de Lavage des Mains"
      },
      
      tk_train_title: "Annexe C : Registre de Formation",
      col_employee: "Nom de l'Employé",
      col_train_desc: "Description de la Formation"
    }
  },
  pt: {
    nav: {
      builder: "Criador",
      features: "Funcionalidades",
      resources: "Recursos",
      pricing: "Preços",
      about: "Sobre",
      contact: "Contato",
      login: "Entrar",
      getStarted: "Começar"
    },
    hero: {
      title: "Planos HACCP em Minutos.",
      subtitle: "Pare de lutar com documentos Word. Nossa IA gera planos de segurança alimentar prontos para auditoria.",
      cta: "Criar Plano Grátis"
    },
    wizard: {
      title: "Vamos criar o seu plano HACCP",
      subtitle: "Responda a algumas perguntas e nossa IA redigirá um documento completo.",
      start: "Iniciar Criador",
      next: "Próximo",
      back: "Voltar",
      add: "Adicionar",
      generating: "Criando seu plano HACCP...",
      generatingDesc: "Nossa IA está aplicando padrões ao seu contexto de negócios.",
      download: "Baixar PDF",
      success: "Seu rascunho está pronto!",
      step_business: "Contexto de Negócios",
      step_products: "Detalhes do Produto"
    },
    pdf: {
      title: "Plano HACCP",
      subtitle: "Sistema de Gestão de Segurança Alimentar",
      facility: "Nome da Instalação",
      product_scope: "Escopo do Produto",
      date_issue: "Data de Emissão",
      standard: "Padrão",
      disclaimer: "Este documento é um rascunho gerado e deve ser validado por um profissional qualificado.",
      confidential: "CONFIDENCIAL",
      version: "Versão 1.0",
      generated_by: "Gerado por ilovehaccp.com - IA de Segurança Alimentar",
      
      s1_title: "1.0 Visão Geral do Plano",
      s1_executive: "1.1 Resumo Executivo",
      s1_product: "1.2 Descrição do Produto",
      s1_process: "1.3 Narrativa do Processo",
      
      lbl_product_name: "Nome do Produto",
      lbl_description: "Descrição",
      lbl_intended_use: "Uso Pretendido",
      lbl_storage: "Armazenamento",
      
      s2_title: "2.0 Programas de Pré-requisitos (PPR)",
      s2_desc: "Programas fundamentais para controlar perigos gerais de higiene.",
      col_program: "Programa",
      col_details: "Detalhes e Controle",
      
      s3_title: "3.0 Análise de Perigos (Princípio 1 e 2)",
      col_step: "Etapa",
      col_hazards: "Perigos (B/Q/F)",
      col_control: "Medida de Controle",
      col_ccp: "PCC?",
      val_prerequisite: "Pré-requisito",
      
      s4_title: "4.0 Tabela de Controle HACCP (Princípios 3-7)",
      s4_desc: "Plano de controle detalhado para os Pontos Críticos de Controle identificados.",
      lbl_hazard: "PERIGO SIGNIFICATIVO",
      lbl_critical_limit: "Limite Crítico",
      lbl_monitoring: "Monitoramento",
      lbl_corrective: "Ação Corretiva",
      msg_no_ccps: "Nenhum Ponto Crítico de Controle (PCC) identificado. O processo é controlado via PPR.",
      
      sign_prepared: "Preparado por (Líder da Equipe HACCP)",
      sign_approved: "Aprovado por (Gerência)",
      
      tk_title: "Ferramentas: Registros de Monitoramento",
      tk_temp_title: "Apêndice A: Registro de Controle de Temperatura",
      tk_temp_desc: "Use este registro para PCCs (ex: Cozimento, Armazenamento Refrigerado).",
      col_date: "Data",
      col_time: "Hora",
      col_item: "Item/Equipamento",
      col_temp: "Temp (°C)",
      col_action: "Ação",
      col_sign: "Assinatura",
      msg_corrective: "*Ação Corretiva necessária se os Limites Críticos forem violados.",
      
      tk_clean_title: "Apêndice B: Lista de Limpeza Diária",
      col_task: "Tarefa de Limpeza",
      days: { mon: "Seg", tue: "Ter", wed: "Qua", thu: "Qui", fri: "Sex", sat_sun: "Sáb/Dom" },
      tasks: {
        surfaces: "Superfícies e Tábuas de Preparação",
        cooking: "Equipamentos de Cozinha (Fornos/Fogões)",
        fridges: "Refrigeradores e Puxadores",
        sinks: "Pias e Torneiras",
        floors: "Pisos e Ralos",
        waste: "Lixeiras (Esvaziadas e Limpas)",
        handwash: "Estações de Lavagem de Mãos"
      },
      
      tk_train_title: "Apêndice C: Registro de Treinamento",
      col_employee: "Nome do Funcionário",
      col_train_desc: "Descrição do Treinamento"
    }
  }
};