import { Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell, WidthType, BorderStyle, HeadingLevel, AlignmentType, Header, Footer, PageNumber } from "docx";

export async function generateWordDocument(data: any): Promise<Buffer> {
  const { businessName, full_plan } = data;
  const analysis = full_plan.hazard_analysis || [];
  const ccps = full_plan.ccp_summary || [];

  // Helper for simple tables
  const createTwoColTable = (label: string, value: string) => new TableRow({
    children: [
      new TableCell({ width: { size: 30, type: WidthType.PERCENTAGE }, shading: { fill: "F3F4F6" }, children: [new Paragraph({ children: [new TextRun({ text: label, bold: true })] })] }),
      new TableCell({ width: { size: 70, type: WidthType.PERCENTAGE }, children: [new Paragraph(value || "-")] }),
    ],
  });

  const doc = new Document({
    sections: [
      {
        properties: {},
        headers: {
            default: new Header({
                children: [
                    new Paragraph({
                        text: `${businessName} - HACCP Plan`,
                        alignment: AlignmentType.RIGHT,
                        style: "Header"
                    })
                ]
            })
        },
        footers: {
            default: new Footer({
                children: [
                    new Paragraph({
                        alignment: AlignmentType.CENTER,
                        children: [
                            new TextRun("Generated by ilovehaccp.com - Page "),
                            new TextRun({
                                children: [PageNumber.CURRENT],
                            }),
                        ],
                    })
                ]
            })
        },
        children: [
          // Title Page
          new Paragraph({
            text: "HACCP PLAN",
            heading: HeadingLevel.TITLE,
            alignment: AlignmentType.CENTER,
            spacing: { after: 300 }
          }),
          new Paragraph({
            text: `Prepared for: ${businessName}`,
            heading: HeadingLevel.HEADING_2,
            alignment: AlignmentType.CENTER,
            spacing: { after: 100 }
          }),
          new Paragraph({
            text: `Date: ${new Date().toLocaleDateString()}`,
            alignment: AlignmentType.CENTER,
            spacing: { after: 800 }
          }),

          // 1. Plan Overview
          new Paragraph({
            text: "1. Plan Overview",
            heading: HeadingLevel.HEADING_1,
            spacing: { before: 400, after: 200 }
          }),
          new Paragraph({
            text: "Executive Summary",
            heading: HeadingLevel.HEADING_2,
            spacing: { after: 100 }
          }),
          new Paragraph({
            text: full_plan.executive_summary || "No summary provided.",
            spacing: { after: 400 }
          }),

          new Paragraph({
            text: "Product Description",
            heading: HeadingLevel.HEADING_2,
            spacing: { after: 100 }
          }),
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: [
                createTwoColTable("Product Name", data.productName || "HACCP Plan"),
                createTwoColTable("Description", data.productDescription || "-"),
                createTwoColTable("Intended Use", data.intendedUse || "-"),
                createTwoColTable("Storage", data.storageType || "-"),
            ]
          }),
          new Paragraph({ text: "", spacing: { after: 200 } }), // Spacer

          new Paragraph({
            text: "Process Flow Narrative",
            heading: HeadingLevel.HEADING_2,
            spacing: { after: 100 }
          }),
          new Paragraph({
            text: full_plan.process_flow_narrative || "Standard linear flow.",
            spacing: { after: 400 }
          }),

          // 2. Prerequisite Programs
          new Paragraph({
            text: "2. Prerequisite Programs",
            heading: HeadingLevel.HEADING_1,
            spacing: { before: 400, after: 200 }
          }),
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: [
              new TableRow({
                children: [
                  new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: "Program", bold: true })] })] }),
                  new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: "Details", bold: true })] })] }),
                ],
              }),
              ...(full_plan.prerequisite_programs || []).map((p: any) => 
                new TableRow({
                  children: [
                    new TableCell({ children: [new Paragraph(p.program)] }),
                    new TableCell({ children: [new Paragraph(p.details)] }),
                  ],
                })
              )
            ],
          }),

          // 3. Hazard Analysis
          new Paragraph({
            text: "3. Hazard Analysis",
            heading: HeadingLevel.HEADING_1,
            spacing: { before: 400, after: 200 }
          }),
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: [
              new TableRow({
                children: [
                  new TableCell({ width: { size: 20, type: WidthType.PERCENTAGE }, children: [new Paragraph({ children: [new TextRun({ text: "Step", bold: true })] })] }),
                  new TableCell({ width: { size: 30, type: WidthType.PERCENTAGE }, children: [new Paragraph({ children: [new TextRun({ text: "Hazards", bold: true })] })] }),
                  new TableCell({ width: { size: 30, type: WidthType.PERCENTAGE }, children: [new Paragraph({ children: [new TextRun({ text: "Control", bold: true })] })] }),
                  new TableCell({ width: { size: 20, type: WidthType.PERCENTAGE }, children: [new Paragraph({ children: [new TextRun({ text: "CCP?", bold: true })] })] }),
                ],
              }),
              ...analysis.map((item: any) => 
                new TableRow({
                  children: [
                    new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: item.step_name, bold: true })] })] }),
                    new TableCell({ children: [new Paragraph(item.hazards)] }),
                    new TableCell({ children: [new Paragraph(item.control_measure)] }),
                    new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: item.is_ccp ? "YES (CCP)" : "No (PRP)", color: item.is_ccp ? "FF0000" : "000000" })] })] }),
                  ],
                })
              )
            ],
          }),

          // 4. CCP Summary
          new Paragraph({
            text: "4. CCP Summary Plan",
            heading: HeadingLevel.HEADING_1,
            spacing: { before: 400, after: 200 }
          }),
          ...ccps.map((ccp: any, index: number) => [
            new Paragraph({
              text: `CCP #${index + 1}: ${ccp.ccp_step}`,
              heading: HeadingLevel.HEADING_3,
              spacing: { before: 200, after: 100 }
            }),
            new Paragraph({
                children: [
                    new TextRun({ text: "Hazard: ", bold: true }),
                    new TextRun(ccp.hazard)
                ]
            }),
            new Paragraph({
                children: [
                    new TextRun({ text: "Critical Limit: ", bold: true }),
                    new TextRun(ccp.critical_limit)
                ]
            }),
            new Paragraph({
                children: [
                    new TextRun({ text: "Monitoring: ", bold: true }),
                    new TextRun(ccp.monitoring)
                ]
            }),
            new Paragraph({
                children: [
                    new TextRun({ text: "Corrective Action: ", bold: true }),
                    new TextRun(ccp.corrective_action)
                ],
                spacing: { after: 200 }
            })
          ]).flat(),

          // 5. Benchmarking (If available)
          ...(full_plan.benchmarking ? [
              new Paragraph({
                text: "5. Benchmarking & Recommendations",
                heading: HeadingLevel.HEADING_1,
                spacing: { before: 400, after: 200 }
              }),
              new Paragraph({
                  text: `Safety Score: ${full_plan.benchmarking.score}%`,
                  heading: HeadingLevel.HEADING_3
              }),
              new Paragraph({
                  text: full_plan.benchmarking.analysis_summary,
                  spacing: { after: 200 }
              }),
              new Table({
                width: { size: 100, type: WidthType.PERCENTAGE },
                rows: [
                  new TableRow({
                    children: [
                      new TableCell({ width: { size: 20, type: WidthType.PERCENTAGE }, children: [new Paragraph({ children: [new TextRun({ text: "Impact", bold: true })] })] }),
                      new TableCell({ width: { size: 80, type: WidthType.PERCENTAGE }, children: [new Paragraph({ children: [new TextRun({ text: "Recommendation", bold: true })] })] }),
                    ],
                  }),
                  ...full_plan.benchmarking.recommendations.map((rec: any) => 
                    new TableRow({
                      children: [
                        new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: rec.impact.toUpperCase(), bold: true, color: rec.impact === 'High' ? 'FF0000' : '000000' })] })] }),
                        new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: rec.title, bold: true }), new TextRun(`: ${rec.desc}`)] })] }),
                      ],
                    })
                  )
                ],
              })
          ] : []),

          // 6. Toolkit / Logs
          new Paragraph({
            text: "6. Monitoring Logs (Toolkit)",
            heading: HeadingLevel.HEADING_1,
            spacing: { before: 400, after: 200 }
          }),
          new Paragraph({
              text: "Temperature Log",
              heading: HeadingLevel.HEADING_2,
              spacing: { after: 100 }
          }),
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: [
                new TableRow({
                    children: ["Date", "Time", "Item/Unit", "Temp", "Corrective Action", "Sign"].map(t => 
                        new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: t, bold: true })] })] })
                    )
                }),
                ...[...Array(10)].map(() => new TableRow({
                    children: [...Array(6)].map(() => new TableCell({ children: [new Paragraph(" ")] }))
                }))
            ]
          }),
          
          new Paragraph({ text: "", spacing: { after: 200 } }), // Spacer

          new Paragraph({
              text: "Cleaning Schedule",
              heading: HeadingLevel.HEADING_2,
              spacing: { after: 100 }
          }),
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: [
                new TableRow({
                    children: ["Task", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat/Sun"].map(t => 
                        new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: t, bold: true })] })] })
                    )
                }),
                ...["Surfaces", "Equipment", "Floors", "Waste", "Handwash Sinks"].map(task => new TableRow({
                    children: [
                        new TableCell({ children: [new Paragraph(task)] }),
                        ...[...Array(6)].map(() => new TableCell({ children: [new Paragraph(" ")] }))
                    ]
                }))
            ]
          }),
        ],
      },
    ],
  });

  return Packer.toBuffer(doc);
}