
-- Seed Articles (v3 Unique Images & Improved Flow)
-- Generated by scripts/generate_sql_seed.js
-- RUN THIS IN SUPABASE SQL EDITOR


INSERT INTO articles (slug, title, category, read_time, excerpt, image, content, published_at)
VALUES (
  'digital-vs-paper-records', 
  'Digital Records in Auditing: Why Electronic Documentation Reigns Supreme', 
  'Compliance', 
  '42 min read', 
  'Discover the benefits of digital records in auditing, including enhanced accuracy, efficiency, and compliance with regulatory frameworks. This article explores the shift from paper to digital records, highlighting the advantages and best practices for implementation.', 
  NULL, 
  $content$
    slug: "digital-vs-paper-records",
    title: "Digital Records in Auditing: Why Electronic Documentation Reigns Supreme",
    category: "Compliance",
    readTime: "42 min read",
    excerpt: "Discover the benefits of digital records in auditing, including enhanced accuracy, efficiency, and compliance with regulatory frameworks. This article explores the shift from paper to digital records, highlighting the advantages and best practices for implementation.",
    publishedAt: "Jan 12, 2026",
    content: `$content$, 
  'Jan 12, 2026'
)
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  category = EXCLUDED.category,
  read_time = EXCLUDED.read_time,
  excerpt = EXCLUDED.excerpt,
  image = EXCLUDED.image,
  content = EXCLUDED.content,
  published_at = EXCLUDED.published_at;
