import React from "react";
import { View, Text, StyleSheet } from "@react-pdf/renderer";
import { HACCP_THEME as T } from "../theme";

const styles = StyleSheet.create({
  footer: {
    position: "absolute",
    left: T.spacing.pagePadding,
    right: T.spacing.pagePadding,
    bottom: T.spacing.pagePadding - 10,
    borderTopWidth: T.borders.width,
    borderTopColor: T.colors.border,
    paddingTop: 6,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  left: { fontSize: 8, color: T.colors.muted },
  right: { fontSize: 8, color: T.colors.muted },
});

export function PdfFooter() {
  return (
    <View style={styles.footer} fixed>
      <Text style={styles.left}>
        Generated by iLoveHACCP — Draft document for review purposes only
      </Text>
      <Text
        style={styles.right}
        render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`}
      />
    </View>
  );
}
