export const metadata = {
  title: 'Terms of Service | ilovehaccp.com',
  description: 'Terms and conditions for using our AI-powered HACCP builder.',
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-slate-50 py-16 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto bg-white p-8 md:p-12 rounded-3xl shadow-xl prose prose-slate prose-headings:text-slate-900 prose-p:text-slate-600">
        <h1 className="text-4xl font-extrabold mb-4">Terms of Service</h1>
        <p className="lead text-xl text-slate-500 mb-8 border-b pb-8">
          <strong>Effective Date:</strong> December 30, 2025
        </p>

        <div className="bg-amber-50 border-l-4 border-amber-500 p-6 my-8 not-prose rounded-r-xl">
          <h3 className="text-amber-800 font-bold text-lg mb-2">CRITICAL DISCLAIMER: AI-GENERATED CONTENT</h3>
          <p className="text-amber-700 text-sm leading-relaxed">
            The documents generated by ilovehaccp.com are created by Artificial Intelligence based on your inputs. 
            <strong>They are strictly templates/drafts and do NOT constitute a finalized legal or safety document.</strong> 
            You (the User) maintain 100% responsibility for reviewing, validating, and implementing the plan in accordance with your local laws and specific operational realities. 
            We are a software provider, not a food safety consultancy.
          </p>
        </div>

        <h2>1. Agreement to Terms</h2>
        <p>
          By accessing, browsing, or using ilovehaccp.com (&quot;Service&quot;), you acknowledge that you have read, understood, and agree to be bound by these Terms of Service (&quot;Terms&quot;). If you do not agree to these Terms, you may not use the Service.
        </p>

        <h2>2. Service Description & Limitations</h2>
        <p>
          ilovehaccp.com provides an AI-powered tool to assist food businesses in drafting Hazard Analysis and Critical Control Point (HACCP) plans.
        </p>
        <ul>
          <li><strong>No Professional Advice:</strong> The Service is not a substitute for professional advice from a certified Food Safety Consultant or Legal Counsel.</li>
          <li><strong>Free Tier Disclaimer:</strong> Any documents generated under the &quot;Free&quot; or &quot;Preview&quot; tier are provided &quot;AS IS&quot; for educational and drafting purposes only. They are strictly NOT intended for official regulatory submission without professional validation. You assume full risk for their use.</li>
          <li><strong>User Verification Requirement:</strong> You acknowledge that Artificial Intelligence can make errors (&quot;hallucinations&quot;). You agree to manually verify every Critical Control Point (CCP), Critical Limit (e.g., temperatures), and monitoring procedure against your local enforcement agency&apos;s specific standards before implementation.</li>
          <li><strong>Audit Guarantee:</strong> We expressly disclaim any guarantee that a plan generated by our Service will pass an audit or inspection. Compliance is a dynamic process dependent on physical implementation, not just documentation.</li>
        </ul>

        <h2>3. Limitation of Liability</h2>
        <p className="uppercase font-bold text-sm text-slate-400 tracking-wider">Please read this section carefully.</p>
        <p>
          To the maximum extent permitted by applicable law, in no event shall ilovehaccp.com, its directors, employees, partners, agents, suppliers, or affiliates, be liable for any:
        </p>
        <ul>
          <li><strong>Indirect Damages:</strong> Indirect, incidental, special, consequential, or punitive damages, including without limitation, loss of profits, data, use, goodwill, or business interruption.</li>
          <li><strong>Food Safety Incidents:</strong> Any illness, injury, death, or health-related issue resulting from the consumption of food produced by your business, regardless of whether a plan from our Service was implemented.</li>
          <li><strong>Audit Failures:</strong> Fines, penalties, closure orders, or legal costs incurred due to regulatory non-compliance.</li>
        </ul>
        <p>
          <strong>Liability Cap:</strong> Our total liability to you for any claims arising out of or relating to these Terms or your use of the Service shall strictly not exceed the amount you paid to us in the 12 months prior to the claim.
        </p>

        <h2>4. User Responsibilities & Indemnification</h2>
        <p>
          You agree to defend, indemnify, and hold harmless ilovehaccp.com from and against any and all claims, damages, obligations, losses, liabilities, costs, and expenses (including attorney&apos;s fees) arising from:
        </p>
        <ul>
          <li>Your use of and access to the Service.</li>
          <li>Your violation of any term of these Terms.</li>
          <li>The implementation (or lack thereof) of any food safety procedures in your business.</li>
          <li>Any claim that your business caused harm to a third party (e.g., a customer).</li>
        </ul>

        <h2>5. Purchases & Refunds</h2>
        <ul>
          <li><strong>Pricing:</strong> Prices are subject to change without notice.</li>
          <li><strong>Refund Policy:</strong> Due to the digital nature of the content (instant access to the full plan), <strong>all sales are final and non-refundable</strong> once the document has been generated or downloaded, unless required by law.</li>
          <li><strong>Payment Processing:</strong> We use third-party processors (e.g., Stripe). We do not store your credit card details.</li>
        </ul>

        <h2>6. Intellectual Property</h2>
        <p>
          The underlying software, code, and design of the Service are the property of ilovehaccp.com. 
          Upon purchase, you are granted a non-exclusive, perpetual, worldwide license to use the generated HACCP documents for your own business purposes. You may edit, print, and share them with your staff and auditors. You may NOT resell the generated plans as a service to third parties (unless on an Enterprise agency plan).
        </p>

        <h2>7. Governing Law</h2>
        <p>
          These Terms shall be governed and construed in accordance with the laws of the jurisdiction in which our company is registered, without regard to its conflict of law provisions.
        </p>

        <h2>8. Contact</h2>
        <p className="text-slate-600 mb-4">
          For legal notices or support questions, please contact us at: <a href="mailto:support@ilovehaccp.com" className="text-blue-600 hover:underline">support@ilovehaccp.com</a>
        </p>
      </div>
    </div>
  );
}
