export const metadata = {
  title: 'Terms and Conditions | ilovehaccp.com',
  description: 'Terms and conditions for using our technology-powered HACCP builder and consultancy services.',
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#FAFAFA]">
      <div className="max-w-5xl mx-auto py-20 px-6">
        {/* Header */}
        <div className="mb-16">
          <span className="text-blue-600 font-bold tracking-wider uppercase text-sm mb-2 block">Legal Agreement</span>
          <h1 className="text-5xl font-black text-slate-900 mb-6 tracking-tight">Terms and Conditions</h1>
          <div className="flex items-center gap-4 text-slate-500 font-medium">
            <span>Effective: January 3, 2026</span>
            <span className="w-1 h-1 bg-slate-300 rounded-full"></span>
            <span>Version 3.0</span>
          </div>
        </div>

        <div className="grid lg:grid-cols-12 gap-12">
          {/* Main Content */}
          <div className="lg:col-span-8 space-y-16">
            
            {/* Section 0: Critical Technology Disclaimer (Essential for HACCP tools) */}
      <section id="disclaimer" className="mb-12">
        <h2 className="text-2xl font-bold mb-4">No Legal Advice & No Guarantee</h2>
        <p className="mb-4">
          The materials and HACCP plans generated by iLoveHACCP are for informational and guidance purposes only. They are designed to assist in the creation of food safety documentation but do not constitute legal advice, regulatory guarantees, or a certification of compliance.
        </p>
        <p className="mb-4">
          You acknowledge that:
        </p>
        <ul className="list-disc pl-6 mb-4 space-y-2">
          <li><strong>Local Variation:</strong> Food safety regulations vary significantly by jurisdiction (country, state, county). Our automated tools use general international principles (Codex Alimentarius) which may not satisfy your specific local health authority requirements.</li>
          <li><strong>Operator Responsibility:</strong> You are solely responsible for validating the generated plan against your actual operations, verifying critical limits, and ensuring all hazards are adequately controlled.</li>
          <li><strong>Professional Review:</strong> We strongly recommend having your final plan reviewed by a qualified local food safety consultant or environmental health officer before operational use.</li>
        </ul>
      </section>

            <Section 
              number="1"
              title="Agreement to Terms"
              content={
                <p>
                  By accessing ilovehaccp.com ("Website", "Service"), you acknowledge that you have read, understood, and agree to be bound by these Terms and Conditions. These terms, along with our Privacy Statement and Cookie Policy, constitute a binding agreement between you and ilovehaccp.com.
                </p>
              }
              summary="By using our site, you agree to follow these rules."
            />

            <Section 
              number="2"
              title="Electronic Communication"
              content={
                <p>
                  By using this Website or communicating with us by electronic means, you agree and acknowledge that we may communicate with you electronically on our website or by sending an email to you, and you agree that all agreements, notices, disclosures, and other communications that we provide to you electronically satisfy any legal requirement that such communications be in writing.
                </p>
              }
              summary="We will communicate via email and through the site, and that counts as 'in writing' legally."
            />

            <Section 
              number="3"
              title="Intellectual Property"
              content={
                <>
                  <p>
                    We or our licensors own and control all of the copyright and other intellectual property rights in the Website and the data, information, and other resources displayed by or accessible within the Website.
                  </p>
                  <p className="mt-4 font-bold text-slate-900">Limited License:</p>
                  <p>
                    Unless specific content indicates otherwise, you are granted a limited, non-exclusive, non-sublicensable, and non-transferable license to use the resources solely for your personal or internal business purposes related to food safety management. You may not copy, reproduce, or commercialize the underlying software or proprietary models.
                  </p>
                </>
              }
              summary="We own the technology. You get a license to use it for your business safety plans, but you can't sell our software as your own."
            />

            <Section 
              number="4"
              title="Third-party Property"
              content={
                <p>
                  Our Website may include hyperlinks or other references to other party’s websites. We do not monitor or review the content of other party’s websites which are linked to from this Website. We are not responsible for the privacy practices or content of these sites.
                </p>
              }
              summary="If we link to other sites, we aren't responsible for what happens there."
            />

            <Section 
              number="5"
              title="Responsible Use"
              content={
                <>
                  <p>
                    By visiting our Website, you agree to use it only for the purposes intended and as permitted by these Terms. You must not use our Website to:
                  </p>
                  <ul className="list-disc pl-5 mt-4 space-y-2">
                    <li>Publish or distribute malicious software (viruses, etc.).</li>
                    <li>Conduct systematic or automated data collection activities (scraping, data mining).</li>
                    <li>Engage in any activity that causes, or may cause, damage to the Website or interference with its performance.</li>
                  </ul>
                </>
              }
              summary="Don't hack us, don't scrape our data, and don't use the site to do anything illegal."
            />

            <Section 
              number="6"
              title="Idea Submission"
              content={
                <p>
                  Do not submit any ideas, inventions, works of authorship, or other information that can be considered your own intellectual property that you would like to present to us unless we have first signed an agreement regarding the intellectual property or a non-disclosure agreement. If you disclose it without such agreement, you grant us a worldwide, irrevocable, non-exclusive, royalty-free license to use it.
                </p>
              }
              summary="Don't send us 'secret ideas' unless we have an NDA. If you send them anyway, we can use them."
            />

            <Section 
              number="7"
              title="Termination of Use"
              content={
                <p>
                  We may, in our sole discretion, at any time modify or discontinue access to, temporarily or permanently, the Website or any Service thereon. You agree that we will not be liable to you or any third party for any such modification, suspension or discontinuance of your access to, or use of, the Website or any content that you may have shared on the Website.
                </p>
              }
              summary="We can stop the service or ban users if needed, without being held liable."
            />

            <Section 
              number="8"
              title="No Guarantee of Compliance"
              content={
        <p className="mb-4">
          <strong>We do not guarantee that any HACCP plan or document generated by this Service will pass any specific audit, inspection, or regulatory review.</strong> Food safety regulations (including EC 852/2004, UK FSA, EHO, BRCGS, SQF) vary significantly by jurisdiction and inspector interpretation. The documents provided are templates based on general principles and must be verified, customized, and validated by a qualified professional for your specific facility. Failure to pass an audit is the sole responsibility of the User.
        </p>
              }
              summary="We give you a head start, but passing the inspection is 100% your job."
            />

            <Section 
              number="9"
              title="Food Safety Liability Waiver"
              content={
                <p>
                  ilovehaccp.com and its operators shall not be liable for any foodborne illness, injury, death, allergic reaction, or public health incident resulting from the consumption of products produced by your business. The use of our software does not substitute for active food safety management, daily monitoring, and staff training. You acknowledge that you are solely responsible for the safety of the food you produce.
                </p>
              }
              summary="If someone gets sick from your food, you cannot blame our software."
            />

            <Section 
              number="10"
              title="Indemnification"
              content={
                <p>
                  You agree to indemnify, defend, and hold harmless ilovehaccp.com, its officers, directors, employees, agents, and licensors from and against any and all claims, liabilities, damages, losses, costs, expenses, or fees (including reasonable attorneys' fees) that such parties may incur as a result of or arising from your use of the Service, your violation of these Terms, or your violation of any rights of another party (including regulatory bodies).
                </p>
              }
              summary="If you get sued or fined and try to drag us into it, you have to pay our legal bills."
            />

            <Section 
              number="11"
              title="Warranties and Liability"
              content={
                <>
                  <p className="font-bold">The Website and all content are provided on an "as is" and "as available" basis.</p>
                  <p className="mt-4">
                    Nothing on this Website constitutes or is meant to constitute, legal, financial or medical advice of any kind. If you require advice you should consult an appropriate professional.
                  </p>
                  <p className="mt-4 uppercase text-xs font-bold tracking-tight bg-slate-100 p-4 rounded-lg">
                    TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, WE WILL NOT BE LIABLE FOR ANY DIRECT OR INDIRECT LOSS OR DAMAGE (INCLUDING LOSS OF PROFITS, REVENUE, OR DATA) ARISING OUT OF OR IN CONNECTION WITH THE USE OF OUR SERVICES. OUR MAXIMUM LIABILITY TO YOU FOR ALL DAMAGES SHALL BE LIMITED TO THE TOTAL PRICE PAID BY YOU TO US FOR THE PRODUCT OR SERVICE.
                  </p>
                </>
              }
              summary="We aren't your lawyer or your safety officer. If something goes wrong, our maximum liability is limited to what you paid us."
            />

            <Section 
              number="12"
              title="Export Restrictions & Legal Compliance"
              content={
                <p>
                  Access to the Website from territories or countries where the Content or purchase of the products or Services sold on the Website is illegal is prohibited. You must not use this Website in violation of export laws and regulations.
                </p>
              }
              summary="Don't use our site if it's illegal in your country."
            />

            <Section 
              number="13"
              title="Language"
              content={
                <p>
                  These Terms and Conditions will be interpreted and construed exclusively in English, Portuguese, Spanish, and French. All notices and correspondence will be written exclusively in those languages.
                </p>
              }
              summary="We operate in 4 main languages: EN, PT, ES, FR."
            />

            <Section 
              number="14"
              title="Choice of Law and Jurisdiction"
              content={
                <p>
                  These Terms and Conditions shall be governed by the laws of the jurisdiction in which our business is registered. Any disputes relating to these Terms and Conditions shall be subject to the jurisdiction of the courts of such country.
                </p>
              }
              summary="Legal disputes will be handled in the country where we are registered."
            />

            <Section 
              number="15"
              title="Contact Information"
              content={
                <div className="bg-slate-50 p-6 rounded-xl border border-slate-200">
                  <p className="text-slate-700"><strong>Website:</strong> ilovehaccp.com</p>
                  <p className="text-slate-700"><strong>Email:</strong> support@ilovehaccp.com</p>
                </div>
              }
            />

          </div>

          {/* Sidebar Navigation */}
          <div className="hidden lg:block lg:col-span-4 relative">
            <div className="sticky top-24 space-y-8">
              <div className="bg-white rounded-2xl p-6 shadow-xl shadow-slate-200/50 border border-slate-100">
                <h3 className="font-bold text-slate-900 mb-4">Quick Links</h3>
                <nav className="space-y-3 text-sm font-medium text-slate-500">
                  <a href="#" className="block hover:text-blue-600 transition-colors">Technology Disclaimer</a>
                  <a href="#" className="block hover:text-blue-600 transition-colors">3. Intellectual Property</a>
                  <a href="#" className="block hover:text-blue-600 transition-colors">5. Responsible Use</a>
                  <a href="#" className="block hover:text-blue-600 transition-colors">8. Liability</a>
                  <a href="#" className="block hover:text-blue-600 transition-colors">11. Jurisdiction</a>
                </nav>
              </div>
              
              <div className="bg-blue-600 rounded-2xl p-6 text-white shadow-xl shadow-blue-500/20">
                <h3 className="font-bold mb-2">Legal Questions?</h3>
                <p className="text-blue-100 text-sm mb-4">Our compliance team is here to clarify any points in this agreement.</p>
                <a href="mailto:support@ilovehaccp.com" className="inline-block bg-white text-blue-600 px-4 py-2 rounded-lg text-sm font-bold hover:bg-blue-50 transition-colors">
                  Email Support
                </a>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>
  );
}

function Section({ number, title, content, summary }: any) {
  return (
    <div className="group relative">
      <div className="absolute -left-12 top-0 text-slate-200 font-black text-6xl opacity-50 select-none hidden xl:block">
        {number}
      </div>
      <h2 className="text-2xl font-bold text-slate-900 mb-6 flex items-center gap-3">
        <span className="bg-slate-100 text-slate-500 text-sm px-2 py-1 rounded-md font-mono xl:hidden">#{number}</span>
        {title}
      </h2>
      <div className="prose prose-slate max-w-none prose-p:leading-relaxed prose-a:text-blue-600">
        {content}
      </div>
      {summary && (
        <div className="mt-6 bg-slate-50 border-l-4 border-slate-300 p-4 rounded-r-lg">
          <p className="text-sm text-slate-600 font-medium m-0">
            <span className="uppercase text-xs font-bold text-slate-400 tracking-wider block mb-1">Plain English Summary</span>
            {summary}
          </p>
        </div>
      )}
    </div>
  );
}
