const fs = require('fs');
const path = require('path');

const tsPath = path.join(__dirname, '../src/data/articles.ts');
const sqlPath = path.join(__dirname, '../seed_articles.sql');

async function run() {
  console.log("Parsing articles.ts via regex blocks for SQL generation...");
  
  const content = fs.readFileSync(tsPath, 'utf-8');

  // Split by article objects (robust regex for { preceded by whitespace/newline)
  const blocks = content.split(/\n\s*\{/).filter(b => b.includes('slug:') || b.includes('"slug":') || b.includes("'slug':"));
  console.log(`Found ${blocks.length} blocks.`);

  const escapeLiteral = (str) => {
    if (str === null || str === undefined) return 'NULL';
    return "'" + str.replace(/'/g, "''") + "'";
  };

  const stream = fs.createWriteStream(sqlPath);

  stream.write(`
-- Seed Articles (v3 Unique Images & Improved Flow)
-- Generated by scripts/generate_sql_seed.js
-- RUN THIS IN SUPABASE SQL EDITOR

`);

  for (let block of blocks) {
    const slug = (block.match(/slug:\s*['"](.*?)['"]/) || [])[1];
    const title = (block.match(/title:\s*["'](.*?)["']/) || [])[1];
    const category = (block.match(/category:\s*['"](.*?)['"]/) || [])[1];
    const readTime = (block.match(/readTime:\s*['"](.*?)['"]/) || [])[1];
    const excerpt = (block.match(/excerpt:\s*["']([\s\S]*?)["']/) || [])[1];
    const image = (block.match(/image:\s*['"](.*?)['"]/) || [])[1];
    const publishedAt = (block.match(/publishedAt:\s*['"](.*?)['"]/) || [])[1];
    
    // Extract content (everything between content: ` and `, )
    const contentStart = block.indexOf('content: `') + 10;
    const contentEnd = block.lastIndexOf('`,');
    const articleContent = block.substring(contentStart, contentEnd);

    if (!slug || !title) continue;

    const sql = `
INSERT INTO articles (slug, title, category, read_time, excerpt, image, content, published_at)
VALUES (
  ${escapeLiteral(slug)}, 
  ${escapeLiteral(title)}, 
  ${escapeLiteral(category)}, 
  ${escapeLiteral(readTime)}, 
  ${escapeLiteral(excerpt)}, 
  ${escapeLiteral(image)}, 
  $content$${articleContent}$content$, 
  ${escapeLiteral(publishedAt)}
)
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  category = EXCLUDED.category,
  read_time = EXCLUDED.read_time,
  excerpt = EXCLUDED.excerpt,
  image = EXCLUDED.image,
  content = EXCLUDED.content,
  published_at = EXCLUDED.published_at;
`;
    stream.write(sql);
  }

  stream.end();
  console.log(`SQL seed generated at ${sqlPath}. Total articles: ${blocks.length}`);
}

run();
