const fs = require('fs');
const path = require('path');

// Read articles using the same hack
const tsPath = path.join(__dirname, '../src/data/articles.ts');
const jsPath = path.join(__dirname, 'temp_articles_seed.cjs');
const sqlPath = path.join(__dirname, '../seed_articles.sql');

let content = fs.readFileSync(tsPath, 'utf-8');

const marker = 'export const articles';
const parts = content.split(marker);

if (parts.length < 2) {
    console.error("Could not find 'export const articles' marker");
    process.exit(1);
}

// Take the part after the marker and prepend 'const articles'
// This effectively drops everything before 'export const articles' (imports, interfaces)
let jsContent = 'const articles' + parts[1];

// Remove type annotation ": Article[]"
jsContent = jsContent.replace(/:\s*Article\[\]/g, '');

// Clean up any other potential TS syntax or exports if they appear later (unlikely for this file structure)
// But wait, the file ends with `},];` usually.

jsContent += '\nmodule.exports = { articles };';

fs.writeFileSync(jsPath, jsContent);

try {
    const { articles } = require('./temp_articles_seed.cjs');
    console.log(`Generating SQL for ${articles.length} articles...`);

    const escapeLiteral = (str) => {
      if (str === null || str === undefined) return 'NULL';
      return "'" + str.replace(/'/g, "''") + "'";
    };

    const stream = fs.createWriteStream(sqlPath);

    stream.write(`
-- Seed Articles
-- Generated by scripts/generate_sql_seed.js
-- RUN THIS IN SUPABASE SQL EDITOR

`);

    for (const article of articles) {
      const slug = escapeLiteral(article.slug);
      const title = escapeLiteral(article.title);
      const category = escapeLiteral(article.category);
      const read_time = escapeLiteral(article.readTime);
      const excerpt = escapeLiteral(article.excerpt);
      const image = escapeLiteral(article.image);
      const published_at = escapeLiteral(article.publishedAt);
      
      const contentSql = `$content$${article.content}$content$`;

      const sql = `
INSERT INTO articles (slug, title, category, read_time, excerpt, image, content, published_at)
VALUES (${slug}, ${title}, ${category}, ${read_time}, ${excerpt}, ${image}, ${contentSql}, ${published_at})
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  category = EXCLUDED.category,
  read_time = EXCLUDED.read_time,
  excerpt = EXCLUDED.excerpt,
  image = EXCLUDED.image,
  content = EXCLUDED.content,
  published_at = EXCLUDED.published_at;
`;
      stream.write(sql);
    }

    stream.end();
    console.log(`SQL seed generated at ${sqlPath}`);

} catch (e) {
    console.error("Error parsing generated JS:", e);
} finally {
    if (fs.existsSync(jsPath)) {
        fs.unlinkSync(jsPath);
    }
}